MODULE SURFTSTP_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SURF, ONLY : TSURF

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_LOCAL_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_DDH_TYPE_MOD,        ONLY : DDH_SURF_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFTSTP_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS, ON_GPU)

TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS
LOGICAL                       , INTENT(IN)    :: ON_GPU

IF (ON_GPU) THEN
  CALL SURFTSTP_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)
ELSE
  CALL SURFTSTP_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)
ENDIF

END SUBROUTINE SURFTSTP_LAYER_PARALLEL

SUBROUTINE SURFTSTP_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)
USE FIELD_ACCESS_MODULE, ONLY : SGET_DEVICE_DATA_RDWR
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
     &               NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, NDHVWLS, NDHFWLS, &
     &               NDHVBIOS, NDHFBIOS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESICE, LESURF, NCWS

TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
LOGICAL :: LNEMOICETHK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PINTER_PSSDP2(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PINTER_PSSDP3(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_GELAT(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_PMU0M(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_PGEMU(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUXL_ZPAPSRF(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PLDEPTH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCLAKE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCUR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PZO(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFRTH(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_ZFRTH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFPLCL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFPLSL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFPLCN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFPLSN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFTG12(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFWROD(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFWRO1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFWG12(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFWMLT(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFWEV(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_ZENES(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PAPRS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PU(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PV(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PT(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRSOTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PSLRFLTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PANDAYVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PANFMVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZCVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PSNS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PRSN(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PWSN(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PWL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZWLMX(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZEVAPSNW(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZTHKICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSDOR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PSST(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTRTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PVSTRTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PAHFSTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PEVAPTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PCIL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PLAILC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PLAIHC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTSN(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PASN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTSA(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTIA(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PWSA(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLMNW(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLWML(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLBOT(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLSF(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PHLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PHLML(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCVL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PHO(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PHO_INV(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PDO(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_POCDEPTH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PUO0(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PVO0(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PUOC(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PVOC(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTO0(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PSO0(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PADVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PADVS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PTRI0(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PTRI1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PSWDK_SAVE(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTRC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PVSTRC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTOKES(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PVSTOKES(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PTAUOCX(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PTAUOCY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PPHIOC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWSEMEAN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWSFMEAN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PDIFM(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PDIFT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PDIFS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_POTKE(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PRESPBSTR(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PRESPBSTR2(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOMASS_LAST(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOMASSTR_LAST(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOMASSTR2_LAST(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBLOSSVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBGAINVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PLAI(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOM(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBLOSS(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBGAIN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOMSTR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBIOMSTR2(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSNSE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTSNE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PASNE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PRSNE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWSNE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTSAE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTIAE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWSAE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLICEE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLMNWE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLWMLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLBOTE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLSFE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PHLICEE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PHLMLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUOE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PVOE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTOE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSOE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PLAIE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBSTRE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PBSTR2E1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHTSS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHTTS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHTIS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHSSS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHIIS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHWLS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHBIOS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHVEGS(:,:,:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ITVL(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ITVH(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ISOTY(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_IVEG(:,:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLAND(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLSICE(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLICE(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLNH(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLOCN_KPP(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLAKE(:,:)

#include "surftstp.h"

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_LOKI',0,ZHOOK_HANDLE)

CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP2, PINTER%F_PSSDP2)
CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP3, PINTER%F_PSSDP3)
CALL SGET_DEVICE_DATA_RDWR(PAUX_GELAT, PAUX%F_GELAT)
CALL SGET_DEVICE_DATA_RDWR(PAUX_PMU0M, PAUX%F_PMU0M)
CALL SGET_DEVICE_DATA_RDWR(PAUX_PGEMU, PAUX%F_PGEMU)
CALL SGET_DEVICE_DATA_RDWR(PAUXL_ZPAPSRF, PAUXL%F_ZPAPSRF)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PLDEPTH, PCLIM%F_PLDEPTH)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCLAKE, PCLIM%F_PCLAKE)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCUR, PCLIM%F_PCUR)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PZO, PCLIM%F_PZO)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFRTH, PFLUX%F_PFRTH)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_ZFRTH, PFLUX%F_ZFRTH)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFPLCL, PFLUX%F_PFPLCL)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFPLSL, PFLUX%F_PFPLSL)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFPLCN, PFLUX%F_PFPLCN)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFPLSN, PFLUX%F_PFPLSN)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFTG12, PFLUX%F_PFTG12)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWROD, PFLUX%F_PFWROD)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWRO1, PFLUX%F_PFWRO1)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWG12, PFLUX%F_PFWG12)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWMLT, PFLUX%F_PFWMLT)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWEV, PFLUX%F_PFWEV)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_ZENES, PFLUX%F_ZENES)
CALL SGET_DEVICE_DATA_RDWR(STATE_PAPRS, STATE%F_PAPRS)
CALL SGET_DEVICE_DATA_RDWR(STATE_PU, STATE%F_PU)
CALL SGET_DEVICE_DATA_RDWR(STATE_PV, STATE%F_PV)
CALL SGET_DEVICE_DATA_RDWR(STATE_PT, STATE%F_PT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRTI, PSURFL%F_ZFRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRSOTI, PSURFL%F_ZFRSOTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PSLRFLTI, PSURFL%F_PSLRFLTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PANDAYVT, PSURFL%F_PANDAYVT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PANFMVT, PSURFL%F_PANFMVT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZCVT, PSURFL%F_ZCVT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIVT, PSURFL%F_ZLAIVT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIL, PSURFL%F_ZLAIL)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIH, PSURFL%F_ZLAIH)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PSNS, PSURFL%F_PSNS)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PRSN, PSURFL%F_PRSN)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PWSN, PSURFL%F_PWSN)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PWL, PSURFL%F_PWL)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZWLMX, PSURFL%F_ZWLMX)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZEVAPSNW, PSURFL%F_ZEVAPSNW)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZTHKICE, PSURFL%F_ZTHKICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSDOR, PSURF%F_PSDOR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PSST, PSURF%GSP%F_PSST)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTRTI, PSURF%F_PUSTRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTRTI, PSURF%F_PVSTRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PAHFSTI, PSURF%F_PAHFSTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PEVAPTI, PSURF%F_PEVAPTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PCIL, PSURF%F_PCIL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PLAILC, PSURF%GSD%F_PLAILC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PLAIHC, PSURF%GSD%F_PLAIHC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTSN, PSURF%GSP%F_PTSN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PASN, PSURF%GSP%F_PASN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTL, PSURF%GSP%F_PTL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTSA, PSURF%GSP%F_PTSA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTIA, PSURF%GSP%F_PTIA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PWSA, PSURF%GSP%F_PWSA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLICE, PSURF%GSP%F_PTLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLMNW, PSURF%GSP%F_PTLMNW)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLWML, PSURF%GSP%F_PTLWML)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLBOT, PSURF%GSP%F_PTLBOT)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLSF, PSURF%GSP%F_PTLSF)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PHLICE, PSURF%GSP%F_PHLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PHLML, PSURF%GSP%F_PHLML)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVL, PSURF%F_ZCVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVH, PSURF%F_ZCVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PHO, PSURF%GSD%F_PHO)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PHO_INV, PSURF%GSD%F_PHO_INV)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PDO, PSURF%GSD%F_PDO)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_POCDEPTH, PSURF%GSD%F_POCDEPTH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PUO0, PSURF%GSP%F_PUO0)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PVO0, PSURF%GSP%F_PVO0)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PUOC, PSURF%GSP%F_PUOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PVOC, PSURF%GSP%F_PVOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTO0, PSURF%GSP%F_PTO0)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PSO0, PSURF%GSP%F_PSO0)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PADVT, PSURF%GSD%F_PADVT)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PADVS, PSURF%GSD%F_PADVS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTRI0, PSURF%GSD%F_PTRI0)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTRI1, PSURF%GSD%F_PTRI1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PSWDK_SAVE, PSURF%GSD%F_PSWDK_SAVE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTRC, PSURF%F_PUSTRC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTRC, PSURF%F_PVSTRC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTOKES, PSURF%F_PUSTOKES)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTOKES, PSURF%F_PVSTOKES)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTAUOCX, PSURF%GSD%F_PTAUOCX)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTAUOCY, PSURF%GSD%F_PTAUOCY)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PPHIOC, PSURF%F_PPHIOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSEMEAN, PSURF%F_PWSEMEAN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSFMEAN, PSURF%F_PWSFMEAN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PDIFM, PSURF%F_PDIFM)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PDIFT, PSURF%F_PDIFT)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PDIFS, PSURF%F_PDIFS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_POTKE, PSURF%GSD%F_POTKE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRESPBSTR, PSURF%F_PRESPBSTR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRESPBSTR2, PSURF%F_PRESPBSTR2)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOMASS_LAST, PSURF%F_PBIOMASS_LAST)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOMASSTR_LAST, PSURF%F_PBIOMASSTR_LAST)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOMASSTR2_LAST, PSURF%F_PBIOMASSTR2_LAST)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBLOSSVT, PSURF%F_PBLOSSVT)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBGAINVT, PSURF%F_PBGAINVT)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PLAI, PSURF%F_PLAI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOM, PSURF%F_PBIOM)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBLOSS, PSURF%F_PBLOSS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBGAIN, PSURF%F_PBGAIN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOMSTR, PSURF%F_PBIOMSTR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBIOMSTR2, PSURF%F_PBIOMSTR2)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSNSE1, PSURF%F_PSNSE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTSNE1, PSURF%F_PTSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PASNE1, PSURF%F_PASNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRSNE1, PSURF%F_PRSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSNE1, PSURF%F_PWSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTSAE1, PSURF%F_PTSAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTIAE1, PSURF%F_PTIAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWLE1, PSURF%F_PWLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSAE1, PSURF%F_PWSAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLICEE1, PSURF%F_PTLICEE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLMNWE1, PSURF%F_PTLMNWE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLWMLE1, PSURF%F_PTLWMLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLBOTE1, PSURF%F_PTLBOTE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLSFE1, PSURF%F_PTLSFE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PHLICEE1, PSURF%F_PHLICEE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PHLMLE1, PSURF%F_PHLMLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUOE1, PSURF%F_PUOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVOE1, PSURF%F_PVOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTOE1, PSURF%F_PTOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSOE1, PSURF%F_PSOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PLAIE1, PSURF%F_PLAIE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBSTRE1, PSURF%F_PBSTRE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBSTR2E1, PSURF%F_PBSTR2E1)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTSS, PDDHS%F_PDHTSS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTTS, PDDHS%F_PDHTTS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTIS, PDDHS%F_PDHTIS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHSSS, PDDHS%F_PDHSSS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHIIS, PDDHS%F_PDHIIS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHWLS, PDDHS%F_PDHWLS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHBIOS, PDDHS%F_PDHBIOS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHVEGS, PDDHS%F_PDHVEGS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVL, PSURF%F_ITVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVH, PSURF%F_ITVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ISOTY, PSURF%F_ISOTY)
CALL SGET_DEVICE_DATA_RDWR(PSURF_IVEG, PSURF%F_IVEG)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAND, LLKEYS%F_LLLAND)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLSICE, LLKEYS%F_LLSICE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLICE, LLKEYS%F_LLLICE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLNH, LLKEYS%F_LLNH)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLOCN_KPP, LLKEYS%F_LLOCN_KPP)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAKE, LLKEYS%F_LLLAKE)

DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  IF (LESURF) THEN
    PAUXL_ZPAPSRF(KIDIA:KFDIA,IBL)=STATE_PAPRS(KIDIA:KFDIA,NLEV,IBL)
    PFLUX_ZFRTH(KIDIA:KFDIA,IBL)=PFLUX_PFRTH(KIDIA:KFDIA,NLEV,IBL)
    PSURFL_ZTHKICE(KIDIA:KFDIA,IBL)=1.5_JPRB
    LNEMOICETHK=.FALSE.

    CALL SURFTSTP(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
     & KLON=NPROMA, KLEVS=NCSS, KCWS=NCWS, KTILES=NTILES, &
     & KLEVSN=NCSNEC, KLEVO=NCOM, KLEVI=NLEVI, KSTART=NSTART, KSTEP=NSTEP, &
     & KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, &
     & KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVSSS=NDHVSSS, KDHFSSS=NDHFSSS, &
     & KDHVIIS=NDHVIIS, KDHFIIS=NDHFIIS, &
     & KDHVWLS=NDHVWLS, KDHFWLS=NDHFWLS, &
     & KDHVBIOS=NDHVBIOS, KDHFBIOS=NDHFBIOS, &
     & KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & KVTYPES=NVHILO, &
     & KTVL=PSURF_ITVL(:,IBL), KTVH=PSURF_ITVH(:,IBL), KVEG=PSURF_IVEG(:,:,IBL), KSOTY=PSURF_ISOTY(:,IBL), &
     & PSSDP2=PINTER_PSSDP2(:,:,IBL), PSSDP3=PINTER_PSSDP3(:,:,:,IBL), &
     & PTSPHY=TDT, PSDOR=PSURF_PSDOR(:,IBL), PFRTI=PSURFL_ZFRTI(:,:,IBL), &
     & PSST=PSURF_GSP_PSST(:,IBL), PUSTRTI=PSURF_PUSTRTI(:,:,IBL), PVSTRTI=PSURF_PVSTRTI(:,:,IBL), &
     & PAHFSTI=PSURF_PAHFSTI(:,:,IBL), PEVAPTI=PSURF_PEVAPTI(:,:,IBL), &
     & PSSRFLTI=PSURFL_ZFRSOTI(:,:,IBL), PSLRFLTI=PSURFL_PSLRFLTI(:,:,IBL), &
     & PLAT=PAUX_GELAT(:,IBL), PANFMVT=PSURFL_PANFMVT(:,:,IBL), PANDAYVT=PSURFL_PANDAYVT(:,:,IBL), PMU0=PAUX_PMU0M(:,IBL), &
     & PCVT=PSURFL_ZCVT(:,:,IBL), PLAIVT=PSURFL_ZLAIVT(:,:,IBL), &
     & PLAIL=PSURFL_ZLAIL(:,IBL), PLAIH=PSURFL_ZLAIH(:,IBL), &
     & PCIL=PSURF_PCIL(:,IBL), &
     & PLAILC=PSURF_GSD_PLAILC(:,IBL), PLAIHC=PSURF_GSD_PLAIHC(:,IBL), &
     & LDLAND=LLKEYS_LLLAND(:,IBL), LDSICE=LLKEYS_LLSICE(:,IBL), LDLICE=LLKEYS_LLLICE(:,IBL), &
     & LDSI=LESICE, LDNH=LLKEYS_LLNH(:,IBL), LDOCN_KPP=LLKEYS_LLLOCN_KPP(:,IBL), &
     & PSNM1M=PSURFL_PSNS(:,:,IBL), PTSNM1M=PSURF_GSP_PTSN(:,:,IBL), PASNM1M=PSURF_GSP_PASN(:,IBL), &
     & PRSNM1M=PSURFL_PRSN(:,:,IBL), PWSNM1M=PSURFL_PWSN(:,:,IBL), &
     & PAPRS=PAUXL_ZPAPSRF(:,IBL), PTSKM1M=PSURF_GSP_PTL(:,IBL), &
     & PTSAM1M=PSURF_GSP_PTSA(:,:,IBL), PTIAM1M=PSURF_GSP_PTIA(:,:,IBL), &
     & PWLM1M=PSURFL_PWL(:,IBL), PWSAM1M=PSURF_GSP_PWSA(:,:,IBL), &
     & PTLICEM1M=PSURF_GSP_PTLICE(:,IBL), PTLMNWM1M=PSURF_GSP_PTLMNW(:,IBL), &
     & PTLWMLM1M=PSURF_GSP_PTLWML(:,IBL), PTLBOTM1M=PSURF_GSP_PTLBOT(:,IBL), &
     & PTLSFM1M=PSURF_GSP_PTLSF(:,IBL), &
     & PHLICEM1M=PSURF_GSP_PHLICE(:,IBL), PHLMLM1M=PSURF_GSP_PHLML(:,IBL), &
     & PGEMU=PAUX_PGEMU(:,IBL), &
     & PLDEPTH=PCLIM_PLDEPTH(:,IBL), LDLAKE=LLKEYS_LLLAKE(:,IBL), PCLAKE=PCLIM_PCLAKE(:,IBL), &
     & PRSFC=PFLUX_PFPLCL(:,IBL), PRSFL=PFLUX_PFPLSL(:,IBL), &
     & PSLRFL=PFLUX_ZFRTH(:,IBL), PSSFC=PFLUX_PFPLCN(:,IBL), PSSFL=PFLUX_PFPLSN(:,IBL), &
     & PCVL=PSURF_ZCVL(:,IBL), PCVH=PSURF_ZCVH(:,IBL), PCUR=PCLIM_PCUR(:,IBL), &
     & PWLMX=PSURFL_ZWLMX(:,IBL), PEVAPSNW=PSURFL_ZEVAPSNW(:,IBL), &
     & PUSRF=STATE_PU(:,IBL), PVSRF=STATE_PV(:,IBL), PTSRF=STATE_PT(:,IBL), &
     & PZO=PCLIM_PZO(:,:,IBL), PHO=PSURF_GSD_PHO(:,:,IBL), &
     & PHO_INV=PSURF_GSD_PHO_INV(:,:,IBL), PDO=PSURF_GSD_PDO(:,:,IBL), &
     & POCDEPTH=PSURF_GSD_POCDEPTH(:,IBL), &
     & PUO0=PSURF_GSP_PUO0(:,:,IBL), PVO0=PSURF_GSP_PVO0(:,:,IBL), &
     & PUOC=PSURF_GSP_PUOC(:,:,IBL), PVOC=PSURF_GSP_PVOC(:,:,IBL), &
     & PTO0=PSURF_GSP_PTO0(:,:,IBL), &
     & PSO0=PSURF_GSP_PSO0(:,:,IBL), PADVT=PSURF_GSD_PADVT(:,:,IBL), &
     & PADVS=PSURF_GSD_PADVS(:,:,IBL), PTRI0=PSURF_GSD_PTRI0(:,:,IBL), &
     & PTRI1=PSURF_GSD_PTRI1(:,:,IBL), &
     & PSWDK_SAVE=PSURF_GSD_PSWDK_SAVE(:,:,IBL), PUSTRC=PSURF_PUSTRC(:,IBL), &
     & PVSTRC=PSURF_PVSTRC(:,IBL), &
     & PUSTOKES=PSURF_PUSTOKES(:,IBL), PVSTOKES=PSURF_PVSTOKES(:,IBL), &
     & PTAUOCX=PSURF_GSD_PTAUOCX(:,IBL), PTAUOCY=PSURF_GSD_PTAUOCY(:,IBL), &
     & PPHIOC=PSURF_PPHIOC(:,IBL), &
     & PWSEMEAN=PSURF_PWSEMEAN(:,IBL), PWSFMEAN=PSURF_PWSFMEAN(:,IBL), &
     & LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL_ZTHKICE(:,IBL), &
     & PTSDFL=PFLUX_PFTG12(:,IBL), PROFD=PFLUX_PFWROD(:,IBL), PROFS=PFLUX_PFWRO1(:,IBL), &
     & PWFSD=PFLUX_PFWG12(:,IBL), PMELT=PFLUX_PFWMLT(:,IBL), PFWEV=PFLUX_PFWEV(:,IBL), PENES=PFLUX_ZENES(:,:,IBL), &
     & PDIFM=PSURF_PDIFM(:,:,IBL), PDIFT=PSURF_PDIFT(:,:,IBL), &
     & PDIFS=PSURF_PDIFS(:,:,IBL), POTKE=PSURF_GSD_POTKE(:,:,IBL), &
     & PRESPBSTR=PSURF_PRESPBSTR(:,:,IBL), PRESPBSTR2=PSURF_PRESPBSTR2(:,:,IBL), PBIOMASS_LAST=PSURF_PBIOMASS_LAST(:,:,IBL), &
     & PBIOMASSTR_LAST=PSURF_PBIOMASSTR_LAST(:,:,IBL), PBIOMASSTR2_LAST=PSURF_PBIOMASSTR2_LAST(:,:,IBL), &
     & PBLOSSVT=PSURF_PBLOSSVT(:,:,IBL), PBGAINVT=PSURF_PBGAINVT(:,:,IBL), &
     & PLAI=PSURF_PLAI(:,IBL), PBIOM=PSURF_PBIOM(:,IBL), PBLOSS=PSURF_PBLOSS(:,IBL), PBGAIN=PSURF_PBGAIN(:,IBL), &
     & PBIOMSTR=PSURF_PBIOMSTR(:,IBL), PBIOMSTR2=PSURF_PBIOMSTR2(:,IBL), &
     & PSNE1=PSURF_PSNSE1(:,:,IBL), PTSNE1=PSURF_PTSNE1(:,:,IBL), PASNE1=PSURF_PASNE1(:,IBL), &
     & PRSNE1=PSURF_PRSNE1(:,:,IBL), PWSNE1=PSURF_PWSNE1(:,:,IBL), PTSAE1=PSURF_PTSAE1(:,:,IBL), PTIAE1=PSURF_PTIAE1(:,:,IBL), &
     & PWLE1=PSURF_PWLE1(:,IBL), PWSAE1=PSURF_PWSAE1(:,:,IBL), &
     & PTLICEE1=PSURF_PTLICEE1(:,IBL), PTLMNWE1=PSURF_PTLMNWE1(:,IBL), PTLWMLE1=PSURF_PTLWMLE1(:,IBL), &
     & PTLBOTE1=PSURF_PTLBOTE1(:,IBL), PTLSFE1=PSURF_PTLSFE1(:,IBL), &
     & PHLICEE1=PSURF_PHLICEE1(:,IBL), PHLMLE1=PSURF_PHLMLE1(:,IBL), &
     & PUOE1=PSURF_PUOE1(:,:,IBL), PVOE1=PSURF_PVOE1(:,:,IBL), PTOE1=PSURF_PTOE1(:,:,IBL), PSOE1=PSURF_PSOE1(:,:,IBL), &
     & PLAIE1=PSURF_PLAIE1(:,:,IBL), PBSTRE1=PSURF_PBSTRE1(:,:,IBL), PBSTR2E1=PSURF_PBSTR2E1(:,:,IBL), &
     & PDHTSS=PDDHS_PDHTSS(:,:,:,IBL), PDHTTS=PDDHS_PDHTTS(:,:,:,IBL), PDHTIS=PDDHS_PDHTIS(:,:,:,IBL), &
     & PDHSSS=PDDHS_PDHSSS(:,:,:,IBL), PDHIIS=PDDHS_PDHIIS(:,:,IBL), PDHWLS=PDDHS_PDHWLS(:,:,:,IBL), &
     & PDHBIOS=PDDHS_PDHBIOS(:,:,:,IBL), PDHVEGS=PDDHS_PDHVEGS(:,:,:,IBL))
  ELSE
    PFLUX_PFTG12(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWROD(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWRO1(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWMLT(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWG12(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWEV(KIDIA:KFDIA,IBL)=0._JPRB
  ENDIF
ENDDO

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_LOKI',1,ZHOOK_HANDLE)

END SUBROUTINE SURFTSTP_LAYER_LOKI

SUBROUTINE SURFTSTP_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, NDHVTIS, NDHFTIS, &
     &               NDHVSSS, NDHFSSS, NDHVIIS, NDHFIIS, NDHVWLS, NDHFWLS, &
     &               NDHVBIOS, NDHFBIOS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESICE, LESURF, NCWS

TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
LOGICAL :: LNEMOICETHK
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surftstp.h"

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, LNEMOICETHK, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, PDDHS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  IF ( LESURF ) THEN
    PAUXL%ZPAPSRF(KIDIA:KFDIA)=STATE%PAPRS(KIDIA:KFDIA,NLEV)
    PFLUX%ZFRTH(KIDIA:KFDIA)=PFLUX%PFRTH(KIDIA:KFDIA,NLEV)
    PSURFL%ZTHKICE(KIDIA:KFDIA)=1.5_JPRB
    LNEMOICETHK=.FALSE.

    CALL SURFTSTP(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
     & KLON=NPROMA, KLEVS=NCSS, KCWS=NCWS, KTILES=NTILES, &
     & KLEVSN=NCSNEC, KLEVO=NCOM, KLEVI=NLEVI, KSTART=NSTART, KSTEP=NSTEP, &
     & KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, &
     & KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVSSS=NDHVSSS, KDHFSSS=NDHFSSS, &
     & KDHVIIS=NDHVIIS, KDHFIIS=NDHFIIS, &
     & KDHVWLS=NDHVWLS, KDHFWLS=NDHFWLS, &
     & KDHVBIOS=NDHVBIOS, KDHFBIOS=NDHFBIOS, &
     & KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & KVTYPES=NVHILO, &
     & KTVL=ZSURF%ITVL, KTVH=ZSURF%ITVH, KVEG=ZSURF%IVEG, KSOTY=ZSURF%ISOTY, &
     & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
     & PTSPHY=TDT, PSDOR=ZSURF%PSDOR, PFRTI=PSURFL%ZFRTI, &
     & PSST=ZSURF%GSP%PSST, PUSTRTI=ZSURF%PUSTRTI, PVSTRTI=ZSURF%PVSTRTI, &
     & PAHFSTI=ZSURF%PAHFSTI, PEVAPTI=ZSURF%PEVAPTI, &
     & PSSRFLTI=PSURFL%ZFRSOTI, PSLRFLTI=PSURFL%PSLRFLTI, &
     & PLAT=PAUX%GELAT, PANFMVT=PSURFL%PANFMVT, PANDAYVT=PSURFL%PANDAYVT, PMU0=PAUX%PMU0M, &
     & PCVT=PSURFL%ZCVT, PLAIVT=PSURFL%ZLAIVT, &
     & PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
     & PCIL=ZSURF%PCIL, &
     & PLAILC=ZSURF%GSD%PLAILC, PLAIHC=ZSURF%GSD%PLAIHC, &
     & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
     & LDSI=LESICE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
     & PSNM1M=PSURFL%PSNS, PTSNM1M=ZSURF%GSP%PTSN, PASNM1M=ZSURF%GSP%PASN, &
     & PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN, &
     & PAPRS=PAUXL%ZPAPSRF, PTSKM1M=ZSURF%GSP%PTL, &
     & PTSAM1M=ZSURF%GSP%PTSA, PTIAM1M=ZSURF%GSP%PTIA, &
     & PWLM1M=PSURFL%PWL, PWSAM1M=ZSURF%GSP%PWSA, &
     & PTLICEM1M=ZSURF%GSP%PTLICE, PTLMNWM1M=ZSURF%GSP%PTLMNW, &
     & PTLWMLM1M=ZSURF%GSP%PTLWML, PTLBOTM1M=ZSURF%GSP%PTLBOT, &
     & PTLSFM1M=ZSURF%GSP%PTLSF, &
     & PHLICEM1M=ZSURF%GSP%PHLICE, PHLMLM1M=ZSURF%GSP%PHLML, &
     & PGEMU=PAUX%PGEMU, &
     & PLDEPTH=PCLIM%PLDEPTH, LDLAKE=LLKEYS%LLLAKE, PCLAKE=PCLIM%PCLAKE, &
     & PRSFC=PFLUX%PFPLCL, PRSFL=PFLUX%PFPLSL, &
     & PSLRFL=PFLUX%ZFRTH, PSSFC=PFLUX%PFPLCN, PSSFL=PFLUX%PFPLSN, &
     & PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, PCUR=PCLIM%PCUR, &
     & PWLMX=PSURFL%ZWLMX, PEVAPSNW=PSURFL%ZEVAPSNW, &
     & PUSRF=STATE%PU, PVSRF=STATE%PV, PTSRF=STATE%PT, &
     & PZO=PCLIM%PZO, PHO=ZSURF%GSD%PHO, &
     & PHO_INV=ZSURF%GSD%PHO_INV, PDO=ZSURF%GSD%PDO, &
     & POCDEPTH=ZSURF%GSD%POCDEPTH, &
     & PUO0=ZSURF%GSP%PUO0, PVO0=ZSURF%GSP%PVO0, &
     & PUOC=ZSURF%GSP%PUOC, PVOC=ZSURF%GSP%PVOC, &
     & PTO0=ZSURF%GSP%PTO0, &
     & PSO0=ZSURF%GSP%PSO0, PADVT=ZSURF%GSD%PADVT, &
     & PADVS=ZSURF%GSD%PADVS, PTRI0=ZSURF%GSD%PTRI0, &
     & PTRI1=ZSURF%GSD%PTRI1, &
     & PSWDK_SAVE=ZSURF%GSD%PSWDK_SAVE, PUSTRC=ZSURF%PUSTRC, &
     & PVSTRC=ZSURF%PVSTRC, &
     & PUSTOKES=ZSURF%PUSTOKES, PVSTOKES=ZSURF%PVSTOKES, &
     & PTAUOCX=ZSURF%GSD%PTAUOCX, PTAUOCY=ZSURF%GSD%PTAUOCY, &
     & PPHIOC=ZSURF%PPHIOC, &
     & PWSEMEAN=ZSURF%PWSEMEAN, PWSFMEAN=ZSURF%PWSFMEAN, &
     & LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE, &
     & PTSDFL=PFLUX%PFTG12, PROFD=PFLUX%PFWROD, PROFS=PFLUX%PFWRO1, &
     & PWFSD=PFLUX%PFWG12, PMELT=PFLUX%PFWMLT, PFWEV=PFLUX%PFWEV, PENES=PFLUX%ZENES, &
     & PDIFM=ZSURF%PDIFM, PDIFT=ZSURF%PDIFT, &
     & PDIFS=ZSURF%PDIFS, POTKE=ZSURF%GSD%POTKE, &
     & PRESPBSTR=ZSURF%PRESPBSTR, PRESPBSTR2=ZSURF%PRESPBSTR2, PBIOMASS_LAST=ZSURF%PBIOMASS_LAST, &
     & PBIOMASSTR_LAST=ZSURF%PBIOMASSTR_LAST, PBIOMASSTR2_LAST=ZSURF%PBIOMASSTR2_LAST, &
     & PBLOSSVT=ZSURF%PBLOSSVT, PBGAINVT=ZSURF%PBGAINVT, &
     & PLAI=ZSURF%PLAI, PBIOM=ZSURF%PBIOM, PBLOSS=ZSURF%PBLOSS, PBGAIN=ZSURF%PBGAIN, &
     & PBIOMSTR=ZSURF%PBIOMSTR, PBIOMSTR2=ZSURF%PBIOMSTR2, &
     & PSNE1=ZSURF%PSNSE1, PTSNE1=ZSURF%PTSNE1, PASNE1=ZSURF%PASNE1, &
     & PRSNE1=ZSURF%PRSNE1, PWSNE1=ZSURF%PWSNE1, PTSAE1=ZSURF%PTSAE1, PTIAE1=ZSURF%PTIAE1, &
     & PWLE1=ZSURF%PWLE1, PWSAE1=ZSURF%PWSAE1, &
     & PTLICEE1=ZSURF%PTLICEE1, PTLMNWE1=ZSURF%PTLMNWE1, PTLWMLE1=ZSURF%PTLWMLE1, &
     & PTLBOTE1=ZSURF%PTLBOTE1, PTLSFE1=ZSURF%PTLSFE1, &
     & PHLICEE1=ZSURF%PHLICEE1, PHLMLE1=ZSURF%PHLMLE1, &
     & PUOE1=ZSURF%PUOE1, PVOE1=ZSURF%PVOE1, PTOE1=ZSURF%PTOE1, PSOE1=ZSURF%PSOE1, &
     & PLAIE1=ZSURF%PLAIE1, PBSTRE1=ZSURF%PBSTRE1, PBSTR2E1=ZSURF%PBSTR2E1, &
     & PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, PDHTIS=PDDHS%PDHTIS, &
     & PDHSSS=PDDHS%PDHSSS, PDHIIS=PDDHS%PDHIIS, PDHWLS=PDDHS%PDHWLS, &
     & PDHBIOS=PDDHS%PDHBIOS, PDHVEGS=PDDHS%PDHVEGS)
  ELSE
    PFLUX%PFTG12(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWROD(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWRO1(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWMLT(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWG12(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWEV(KIDIA:KFDIA)=0._JPRB
  ENDIF
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFTSTP_LAYER_OPENMP

SUBROUTINE SURFTSTP_LAYER(YSURF, KIDIA, KFDIA, KLON, KLEVS, KTILES, KLEV, KSTART, KSTEP, &
 & KLEVSN, KLEVI, KLEVO, KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS, &
 & KDHVSSS, KDHFSSS, KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS, KDHVBIOS, KDHFBIOS, &
 & KDHVVEGS, KDHFVEGS, KVTYPES, KCWS, LESICE, PTSPHY, PAUX, PAUXL, PCLIM, &
 & PFLUX, PINTER, STATE, LLKEYS, PSURF, PSURFL, PDDHS)

TYPE(TSURF)                   , INTENT(INOUT) :: YSURF
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KIDIA, KFDIA, KLON, KLEVS, KTILES
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KLEV, KSTART, KSTEP, KLEVSN, KLEVI, KLEVO
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVTSS, KDHFTSS, KDHVTTS, KDHFTTS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVTIS, KDHFTIS, KDHVSSS, KDHFSSS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVIIS, KDHFIIS, KDHVWLS, KDHFWLS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KDHVBIOS, KDHFBIOS, KDHVVEGS, KDHFVEGS
INTEGER(KIND=JPIM)            , INTENT(IN)    :: KVTYPES, KCWS
LOGICAL                       , INTENT(IN)    :: LESICE
REAL(KIND=JPRB)               , INTENT(IN)    :: PTSPHY
TYPE(AUX_TYPE)                , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)     , INTENT(INOUT) :: PAUXL
TYPE(CLIMATE_TYPE)            , INTENT(INOUT) :: PCLIM
TYPE(FLUX_TYPE)               , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)           , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)               , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE(SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: PSURFL
TYPE(DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS

LOGICAL :: LNEMOICETHK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surftstp.h"

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',0,ZHOOK_HANDLE)

PAUXL%ZPAPSRF(KIDIA:KFDIA)=STATE%PAPRS(KIDIA:KFDIA,KLEV)
PFLUX%ZFRTH(KIDIA:KFDIA)=PFLUX%PFRTH(KIDIA:KFDIA,KLEV)
PSURFL%ZTHKICE(KIDIA:KFDIA)=1.5_JPRB
LNEMOICETHK=.FALSE.

CALL SURFTSTP(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
 & KLON=KLON, KLEVS=KLEVS, KCWS=KCWS, KTILES=KTILES, &
 & KLEVSN=KLEVSN, KLEVO=KLEVO, KLEVI=KLEVI, KSTART=KSTART, KSTEP=KSTEP, &
 & KDHVTSS=KDHVTSS, KDHFTSS=KDHFTSS, &
 & KDHVTTS=KDHVTTS, KDHFTTS=KDHFTTS, &
 & KDHVTIS=KDHVTIS, KDHFTIS=KDHFTIS, &
 & KDHVSSS=KDHVSSS, KDHFSSS=KDHFSSS, &
 & KDHVIIS=KDHVIIS, KDHFIIS=KDHFIIS, &
 & KDHVWLS=KDHVWLS, KDHFWLS=KDHFWLS, &
 & KDHVBIOS=KDHVBIOS, KDHFBIOS=KDHFBIOS, &
 & KDHVVEGS=KDHVVEGS, KDHFVEGS=KDHFVEGS, &
 & KVTYPES=KVTYPES, &
 & KTVL=PSURF%ITVL, KTVH=PSURF%ITVH, KVEG=PSURF%IVEG, KSOTY=PSURF%ISOTY, &
 & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
 & PTSPHY=PTSPHY, PSDOR=PSURF%PSDOR, PFRTI=PSURFL%ZFRTI, &
 & PSST=PSURF%GSP%PSST, PUSTRTI=PSURF%PUSTRTI, PVSTRTI=PSURF%PVSTRTI, &
 & PAHFSTI=PSURF%PAHFSTI, PEVAPTI=PSURF%PEVAPTI, &
 & PSSRFLTI=PSURFL%ZFRSOTI, PSLRFLTI=PSURFL%PSLRFLTI, &
 & PLAT=PAUX%GELAT, PANFMVT=PSURFL%PANFMVT, PANDAYVT=PSURFL%PANDAYVT, PMU0=PAUX%PMU0M, &
 & PCVT=PSURFL%ZCVT, PLAIVT=PSURFL%ZLAIVT, &
 & PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
 & PCIL=PSURF%PCIL, &
 & PLAILC=PSURF%GSD%PLAILC, PLAIHC=PSURF%GSD%PLAIHC, &
 & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
 & LDSI=LESICE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
 & PSNM1M=PSURFL%PSNS, PTSNM1M=PSURF%GSP%PTSN, PASNM1M=PSURF%GSP%PASN, &
 & PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN, &
 & PAPRS=PAUXL%ZPAPSRF, PTSKM1M=PSURF%GSP%PTL, &
 & PTSAM1M=PSURF%GSP%PTSA, PTIAM1M=PSURF%GSP%PTIA, &
 & PWLM1M=PSURFL%PWL, PWSAM1M=PSURF%GSP%PWSA, &
 & PTLICEM1M=PSURF%GSP%PTLICE, PTLMNWM1M=PSURF%GSP%PTLMNW, &
 & PTLWMLM1M=PSURF%GSP%PTLWML, PTLBOTM1M=PSURF%GSP%PTLBOT, &
 & PTLSFM1M=PSURF%GSP%PTLSF, &
 & PHLICEM1M=PSURF%GSP%PHLICE, PHLMLM1M=PSURF%GSP%PHLML, &
 & PGEMU=PAUX%PGEMU, &
 & PLDEPTH=PCLIM%PLDEPTH, LDLAKE=LLKEYS%LLLAKE, PCLAKE=PCLIM%PCLAKE, &
 & PRSFC=PFLUX%PFPLCL, PRSFL=PFLUX%PFPLSL, &
 & PSLRFL=PFLUX%ZFRTH, PSSFC=PFLUX%PFPLCN, PSSFL=PFLUX%PFPLSN, &
 & PCVL=PSURF%ZCVL, PCVH=PSURF%ZCVH, PCUR=PCLIM%PCUR, &
 & PWLMX=PSURFL%ZWLMX, PEVAPSNW=PSURFL%ZEVAPSNW, &
 & PUSRF=STATE%PU, PVSRF=STATE%PV, PTSRF=STATE%PT, &
 & PZO=PCLIM%PZO, PHO=PSURF%GSD%PHO, &
 & PHO_INV=PSURF%GSD%PHO_INV, PDO=PSURF%GSD%PDO, &
 & POCDEPTH=PSURF%GSD%POCDEPTH, &
 & PUO0=PSURF%GSP%PUO0, PVO0=PSURF%GSP%PVO0, &
 & PUOC=PSURF%GSP%PUOC, PVOC=PSURF%GSP%PVOC, &
 & PTO0=PSURF%GSP%PTO0, &
 & PSO0=PSURF%GSP%PSO0, PADVT=PSURF%GSD%PADVT, &
 & PADVS=PSURF%GSD%PADVS, PTRI0=PSURF%GSD%PTRI0, &
 & PTRI1=PSURF%GSD%PTRI1, &
 & PSWDK_SAVE=PSURF%GSD%PSWDK_SAVE, PUSTRC=PSURF%PUSTRC, &
 & PVSTRC=PSURF%PVSTRC, &
 & PUSTOKES=PSURF%PUSTOKES, PVSTOKES=PSURF%PVSTOKES, &
 & PTAUOCX=PSURF%GSD%PTAUOCX, PTAUOCY=PSURF%GSD%PTAUOCY, &
 & PPHIOC=PSURF%PPHIOC, &
 & PWSEMEAN=PSURF%PWSEMEAN, PWSFMEAN=PSURF%PWSFMEAN, &
 & LNEMOICETHK=LNEMOICETHK, PTHKICE=PSURFL%ZTHKICE, &
 & PTSDFL=PFLUX%PFTG12, PROFD=PFLUX%PFWROD, PROFS=PFLUX%PFWRO1, &
 & PWFSD=PFLUX%PFWG12, PMELT=PFLUX%PFWMLT, PFWEV=PFLUX%PFWEV, PENES=PFLUX%ZENES, &
 & PDIFM=PSURF%PDIFM, PDIFT=PSURF%PDIFT, &
 & PDIFS=PSURF%PDIFS, POTKE=PSURF%GSD%POTKE, &
 & PRESPBSTR=PSURF%PRESPBSTR, PRESPBSTR2=PSURF%PRESPBSTR2, PBIOMASS_LAST=PSURF%PBIOMASS_LAST, &
 & PBIOMASSTR_LAST=PSURF%PBIOMASSTR_LAST, PBIOMASSTR2_LAST=PSURF%PBIOMASSTR2_LAST, &
 & PBLOSSVT=PSURF%PBLOSSVT, PBGAINVT=PSURF%PBGAINVT, &
 & PLAI=PSURF%PLAI, PBIOM=PSURF%PBIOM, PBLOSS=PSURF%PBLOSS, PBGAIN=PSURF%PBGAIN, &
 & PBIOMSTR=PSURF%PBIOMSTR, PBIOMSTR2=PSURF%PBIOMSTR2, &
 & PSNE1=PSURF%PSNSE1, PTSNE1=PSURF%PTSNE1, PASNE1=PSURF%PASNE1, &
 & PRSNE1=PSURF%PRSNE1, PWSNE1=PSURF%PWSNE1, PTSAE1=PSURF%PTSAE1, PTIAE1=PSURF%PTIAE1, &
 & PWLE1=PSURF%PWLE1, PWSAE1=PSURF%PWSAE1, &
 & PTLICEE1=PSURF%PTLICEE1, PTLMNWE1=PSURF%PTLMNWE1, PTLWMLE1=PSURF%PTLWMLE1, &
 & PTLBOTE1=PSURF%PTLBOTE1, PTLSFE1=PSURF%PTLSFE1, &
 & PHLICEE1=PSURF%PHLICEE1, PHLMLE1=PSURF%PHLMLE1, &
 & PUOE1=PSURF%PUOE1, PVOE1=PSURF%PVOE1, PTOE1=PSURF%PTOE1, PSOE1=PSURF%PSOE1, &
 & PLAIE1=PSURF%PLAIE1, PBSTRE1=PSURF%PBSTRE1, PBSTR2E1=PSURF%PBSTR2E1, &
 & PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, PDHTIS=PDDHS%PDHTIS, &
 & PDHSSS=PDDHS%PDHSSS, PDHIIS=PDDHS%PDHIIS, PDHWLS=PDDHS%PDHWLS, &
 & PDHBIOS=PDDHS%PDHBIOS, PDHVEGS=PDDHS%PDHVEGS)

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',1,ZHOOK_HANDLE)

END SUBROUTINE SURFTSTP_LAYER

END MODULE SURFTSTP_LAYER_MOD
