MODULE SURFRAD_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB, JPRD, JPIB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFRAD_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS, ON_GPU)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
LOGICAL                         , INTENT(IN)    :: ON_GPU

IF (ON_GPU) THEN
  CALL SURFRAD_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)
ELSE
  CALL SURFRAD_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)
ENDIF

END SUBROUTINE SURFRAD_LAYER_PARALLEL

SUBROUTINE SURFRAD_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)
USE FIELD_ACCESS_MODULE, ONLY : SGET_DEVICE_DATA_RDWR
USE YOMDPHY         , ONLY : YSURF, NCSS, NTILES, NPOI, NLEV
USE YOMDIM1S        , ONLY : NPROMA
USE YOEPHY          , ONLY : LERADS, LESNICE
USE YOERAD          , ONLY : NSW, NLWEMISS
USE YOMSURF_SSDP_MOD, ONLY : NSSDP3D
USE YOMRIP          , ONLY : RSTATI, NSSSSS
USE YOMCST          , ONLY : RSIGMA, RDAY
USE YOMLOG1S        , ONLY : LSEMISS
USE YOERDI1S        , ONLY : REMISS

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
INTEGER(KIND=JPIM) :: IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON(12), JK, KULOUT
REAL(KIND=JPRD) :: ZJUL
LOGICAL :: LNEMOLIMALB
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PINTER_PSSDP3(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PALBF(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PALBICEF(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PTVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_ZALCOEFF(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCUR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PASN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_PMU0M(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUXL_ZWND(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_ZWS1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PWSA(:,:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ISOTY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PHLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZALBD(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZALBP(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PALB(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZSPECTRALEMISS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZEMIS(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZALBTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUXL_ZCCNL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUXL_ZCCNO(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PU(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PV(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLNH(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLAND(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFRSO(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFRTH(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSRSOD(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSRTHD(:,:)

#include "surfrad.h"
#include "updcal.intfb.h"
#include "fcttim.h"

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_LOKI',0,ZHOOK_HANDLE)

CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP3, PINTER%F_PSSDP3)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PALBF, PSURF%GSD%F_PALBF)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PALBICEF, PSURF%GSD%F_PALBICEF)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PTVH, PCLIM%F_PTVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_ZALCOEFF, PSURF%GSD%F_ZALCOEFF)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCUR, PCLIM%F_PCUR)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCVH, PCLIM%F_PCVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PASN, PSURF%GSP%F_PASN)
CALL SGET_DEVICE_DATA_RDWR(PAUX_PMU0M, PAUX%F_PMU0M)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTL, PSURF%GSP%F_PTL)
CALL SGET_DEVICE_DATA_RDWR(PAUXL_ZWND, PAUXL%F_ZWND)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_ZWS1, PSURF%GSP%F_ZWS1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PWSA, PSURF%GSP%F_PWSA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ISOTY, PSURF%F_ISOTY)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRTI, PSURFL%F_ZFRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PHLICE, PSURF%GSP%F_PHLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLICE, PSURF%GSP%F_PTLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZALBD, PSURFL%F_ZALBD)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZALBP, PSURFL%F_ZALBP)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PALB, PCLIM%F_PALB)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZSPECTRALEMISS, PSURFL%F_ZSPECTRALEMISS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZEMIS, PSURF%F_ZEMIS)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZALBTI, PSURFL%F_ZALBTI)
CALL SGET_DEVICE_DATA_RDWR(PAUXL_ZCCNL, PAUXL%F_ZCCNL)
CALL SGET_DEVICE_DATA_RDWR(PAUXL_ZCCNO, PAUXL%F_ZCCNO)
CALL SGET_DEVICE_DATA_RDWR(STATE_PU, STATE%F_PU)
CALL SGET_DEVICE_DATA_RDWR(STATE_PV, STATE%F_PV)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLNH, LLKEYS%F_LLNH)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAND, LLKEYS%F_LLLAND)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFRSO, PFLUX%F_PFRSO)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFRTH, PFLUX%F_PFRTH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSRSOD, PSURF%F_PSRSOD)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSRTHD, PSURF%F_PSRTHD)

DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  IF (LERADS) THEN
    PAUXL_ZWND(KIDIA:KFDIA,IBL)=SQRT(STATE_PU(KIDIA:KFDIA,IBL)**2 + STATE_PV(KIDIA:KFDIA,IBL)**2)
    PSURF_GSP_ZWS1(KIDIA:KFDIA,IBL)=PSURF_GSP_PWSA(KIDIA:KFDIA,1,IBL)
    LNEMOLIMALB=.FALSE.
    PSURF_GSD_PALBICEF(KIDIA:KFDIA,IBL) = -999._JPRB

    CALL SURFRAD &
     &     ( YSURF=YSURF, KDD=IDD, KMM=IMM, KMON=IMON  , KSECO=ISEC0 &
     &     , KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA  , KTILES=NTILES , KCSS=NCSS, KSSDP3D=NSSDP3D, KSW=NSW, KLW=NLWEMISS &
     &     , LDNH=LLKEYS_LLNH(:,IBL), LDLAND=LLKEYS_LLLAND(:,IBL) &
     &     , PSSDP3=PINTER_PSSDP3(:,:,:,IBL) &
     &     , PALBF=PSURF_GSD_PALBF(:,IBL), PALBICEF=PSURF_GSD_PALBICEF(:,IBL), PTVH=PCLIM_PTVH(:,IBL) &
     &     , PALCOEFF=PSURF_GSD_ZALCOEFF(:,:,IBL), PCUR=PCLIM_PCUR(:,IBL), PCVH=PCLIM_PCVH(:,IBL) &
     &     , PASN=PSURF_GSP_PASN(:,IBL), PMU0=PAUX_PMU0M(:,IBL), PTS=PSURF_GSP_PTL(:,IBL), PWND=PAUXL_ZWND(:,IBL) &
     &     , PWS1=PSURF_GSP_ZWS1(:,IBL), KSOTY=PSURF_ISOTY(:,IBL) &
     &     , PFRTI=PSURFL_ZFRTI(:,:,IBL), PHLICE=PSURF_GSP_PHLICE(:,IBL), PTLICE=PSURF_GSP_PTLICE(:,IBL) &
     &     , PALBD=PSURFL_ZALBD(:,1:NSW,IBL), PALBP=PSURFL_ZALBP(:,1:NSW,IBL), PALB=PCLIM_PALB(:,IBL) &
     &     , PSPECTRALEMISS=PSURFL_ZSPECTRALEMISS(:,1:NLWEMISS,IBL), PEMIT=PSURF_ZEMIS(:,IBL) &
     &     , PALBTI=PSURFL_ZALBTI(:,:,IBL), PCCNL=PAUXL_ZCCNL(:,IBL), PCCNO=PAUXL_ZCCNO(:,IBL) &
     &     , LNEMOLIMALB=LNEMOLIMALB &
     &     , LESNICE=LESNICE)
  ELSE
    DO JK=1,NTILES
      PSURFL_ZALBTI(KIDIA:KFDIA,JK,IBL)=PSURF_GSD_PALBF(KIDIA:KFDIA,IBL)
    ENDDO
    PCLIM_PALB(KIDIA:KFDIA,IBL)=PSURF_GSD_PALBF(KIDIA:KFDIA,IBL)
    PSURF_ZEMIS(KIDIA:KFDIA,IBL)=REMISS
  ENDIF
  IF (LSEMISS) PSURF_ZEMIS(KIDIA:KFDIA,IBL)=REMISS
  PFLUX_PFRSO(KIDIA:KFDIA,NLEV,IBL)=PSURF_PSRSOD(KIDIA:KFDIA,IBL)*(1._JPRB-PCLIM_PALB(KIDIA:KFDIA,IBL))
  PFLUX_PFRTH(KIDIA:KFDIA,NLEV,IBL)=PSURF_ZEMIS(KIDIA:KFDIA,IBL)* &
     &       (PSURF_PSRTHD(KIDIA:KFDIA,IBL)-RSIGMA*PSURF_GSP_PTL(KIDIA:KFDIA,IBL)**4)
ENDDO

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_LOKI',1,ZHOOK_HANDLE)

END SUBROUTINE SURFRAD_LAYER_LOKI

SUBROUTINE SURFRAD_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)
USE YOMDPHY         , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI, NLEV
USE YOMDIM1S        , ONLY : NPROMA
USE YOEPHY          , ONLY : LERADS, LESNICE
USE YOERAD          , ONLY : NSW, NLWEMISS
USE YOMSURF_SSDP_MOD, ONLY : NSSDP3D
USE YOMRIP          , ONLY : RSTATI, NSSSSS
USE YOMCST          , ONLY : RSIGMA, RDAY
USE YOMLOG1S        , ONLY : LSEMISS
USE YOERDI1S        , ONLY : REMISS

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
INTEGER(KIND=JPIM) :: IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON(12), JK, KULOUT
REAL(KIND=JPRD) :: ZJUL
LOGICAL :: LNEMOLIMALB
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfrad.h"
#include "updcal.intfb.h"
#include "fcttim.h"

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, IDD, IMM, IYY, IINC, ISEC0, IYMD, IHM, IMON, JK, KULOUT, &
!$OMP  & ZJUL, LNEMOLIMALB, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PFLUX, PINTER, STATE, LLKEYS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  IF (LERADS) THEN
    CALL DATTIM(ZJUL, IYMD, IHM)
    IDD=NDD(IYMD)
    IMM=NMM(IYMD)
    IYY=NCCAA(IYMD)
    IINC=0
    ISEC0=MOD(NSSSSS+NINT(RSTATI,JPIB),NINT(RDAY))
    KULOUT=-1_JPIM
    CALL UPDCAL(IDD, IMM, IYY, IINC, IDD, IMM, IYY, IMON, KULOUT)
    PAUXL%ZWND(KIDIA:KFDIA)=SQRT(STATE%PU(KIDIA:KFDIA)**2 + STATE%PV(KIDIA:KFDIA)**2)
    ZSURF%GSP%ZWS1(KIDIA:KFDIA)=ZSURF%GSP%PWSA(KIDIA:KFDIA,1)
    LNEMOLIMALB=.FALSE.
    ZSURF%GSD%PALBICEF(KIDIA:KFDIA) = -999._JPRB

    CALL SURFRAD &
     &     ( YSURF=YSURF, KDD=IDD, KMM=IMM, KMON=IMON  , KSECO=ISEC0 &
     &     , KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA  , KTILES=NTILES , KCSS=NCSS, KSSDP3D=NSSDP3D, KSW=NSW, KLW=NLWEMISS &
     &     , LDNH=LLKEYS%LLNH, LDLAND=LLKEYS%LLLAND &
     &     , PSSDP3=PINTER%PSSDP3 &
     &     , PALBF=ZSURF%GSD%PALBF, PALBICEF=ZSURF%GSD%PALBICEF, PTVH=PCLIM%PTVH &
     &     , PALCOEFF=ZSURF%GSD%ZALCOEFF, PCUR=PCLIM%PCUR, PCVH=PCLIM%PCVH &
     &     , PASN=ZSURF%GSP%PASN, PMU0=PAUX%PMU0M, PTS=ZSURF%GSP%PTL, PWND=PAUXL%ZWND &
     &     , PWS1=ZSURF%GSP%ZWS1, KSOTY=ZSURF%ISOTY &
     &     , PFRTI=PSURFL%ZFRTI, PHLICE=ZSURF%GSP%PHLICE, PTLICE=ZSURF%GSP%PTLICE &
     &     , PALBD=PSURFL%ZALBD(:,1:NSW), PALBP=PSURFL%ZALBP(:,1:NSW), PALB=PCLIM%PALB &
     &     , PSPECTRALEMISS=PSURFL%ZSPECTRALEMISS(:,1:NLWEMISS), PEMIT=ZSURF%ZEMIS &
     &     , PALBTI=PSURFL%ZALBTI, PCCNL=PAUXL%ZCCNL, PCCNO=PAUXL%ZCCNO &
     &     , LNEMOLIMALB=LNEMOLIMALB &
     &     , LESNICE=LESNICE)
  ELSE
    DO JK=1,NTILES
      PSURFL%ZALBTI(KIDIA:KFDIA,JK)=ZSURF%GSD%PALBF(KIDIA:KFDIA)
    ENDDO
    PCLIM%PALB(KIDIA:KFDIA)=ZSURF%GSD%PALBF(KIDIA:KFDIA)
    ZSURF%ZEMIS(KIDIA:KFDIA)=REMISS
  ENDIF
  IF (LSEMISS) ZSURF%ZEMIS(KIDIA:KFDIA)=REMISS
  PFLUX%PFRSO(KIDIA:KFDIA,NLEV)=ZSURF%PSRSOD(KIDIA:KFDIA)*(1._JPRB-PCLIM%PALB(KIDIA:KFDIA))
  PFLUX%PFRTH(KIDIA:KFDIA,NLEV)=ZSURF%ZEMIS(KIDIA:KFDIA)* &
     &       (ZSURF%PSRTHD(KIDIA:KFDIA)-RSIGMA*ZSURF%GSP%PTL(KIDIA:KFDIA)**4)
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFRAD_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFRAD_LAYER_OPENMP

END MODULE SURFRAD_LAYER_MOD
