MODULE SURFBC_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE SURFBC_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS, ON_GPU)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
LOGICAL                         , INTENT(IN)    :: ON_GPU

IF (ON_GPU) THEN
  CALL SURFBC_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)
ELSE
  CALL SURFBC_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)
ENDIF

END SUBROUTINE SURFBC_LAYER_PARALLEL

SUBROUTINE SURFBC_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)
USE FIELD_ACCESS_MODULE, ONLY : SGET_DEVICE_DATA_RDWR
USE YOMDPHY , ONLY : YSURF, NCSNEC, NTILES, NPOI
USE YOMDIM1S, ONLY : NPROMA
USE YOEPHY  , ONLY : LESNICE

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PINTER_PSSDP2(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PTVL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCO2TYP(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PTVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PSOTY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCVL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCUR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PLSM(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCI(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PCLAKE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSDOR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PLAILC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PLAIHC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PLAILI(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PLAIHI(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_ZAVGPARC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PCIL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PHLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_PGEMU(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PSNS(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PWL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PRSN(:,:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ITVL(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ICO2TYP(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ITVH(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ISOTY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCVL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCVH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCUR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZLAILP(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZLAIHP(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZAVGPAR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZWLMX(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZCSN(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLAND(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLSICE(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLICE(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLLAKE(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLNH(:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLOCN_KPP(:,:)

#include "surfbc.h"

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_LOKI',0,ZHOOK_HANDLE)

CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP2, PINTER%F_PSSDP2)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PTVL, PCLIM%F_PTVL)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCO2TYP, PCLIM%F_PCO2TYP)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PTVH, PCLIM%F_PTVH)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PSOTY, PCLIM%F_PSOTY)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCVL, PCLIM%F_PCVL)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCVH, PCLIM%F_PCVH)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCUR, PCLIM%F_PCUR)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PLSM, PCLIM%F_PLSM)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCI, PCLIM%F_PCI)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCLAKE, PCLIM%F_PCLAKE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSDOR, PSURF%F_PSDOR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PLAILC, PSURF%GSD%F_PLAILC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PLAIHC, PSURF%GSD%F_PLAIHC)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PLAILI, PSURFL%F_PLAILI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PLAIHI, PSURFL%F_PLAIHI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_ZAVGPARC, PSURF%GSD%F_ZAVGPARC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PCIL, PSURF%F_PCIL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PHLICE, PSURF%GSP%F_PHLICE)
CALL SGET_DEVICE_DATA_RDWR(PAUX_PGEMU, PAUX%F_PGEMU)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PSNS, PSURFL%F_PSNS)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PWL, PSURFL%F_PWL)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PRSN, PSURFL%F_PRSN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVL, PSURF%F_ITVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ICO2TYP, PSURF%F_ICO2TYP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVH, PSURF%F_ITVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ISOTY, PSURF%F_ISOTY)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVL, PSURF%F_ZCVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVH, PSURF%F_ZCVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCUR, PSURF%F_ZCUR)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIL, PSURFL%F_ZLAIL)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIH, PSURFL%F_ZLAIH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZLAILP, PSURF%F_ZLAILP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZLAIHP, PSURF%F_ZLAIHP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZAVGPAR, PSURF%F_ZAVGPAR)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZWLMX, PSURFL%F_ZWLMX)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRTI, PSURFL%F_ZFRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZCSN, PSURFL%F_ZCSN)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAND, LLKEYS%F_LLLAND)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLSICE, LLKEYS%F_LLSICE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLICE, LLKEYS%F_LLLICE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAKE, LLKEYS%F_LLLAKE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLNH, LLKEYS%F_LLNH)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLOCN_KPP, LLKEYS%F_LLOCN_KPP)

DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL SURFBC(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
   & KLON=NPROMA, KTILES=NTILES, KLEVSN=NCSNEC, &
   & PSSDP2=PINTER_PSSDP2(:,:,IBL), PTVL=PCLIM_PTVL(:,IBL), PCO2TYP=PCLIM_PCO2TYP(:,IBL), &
   & PTVH=PCLIM_PTVH(:,IBL), PSOTY=PCLIM_PSOTY(:,IBL), PSDOR=PSURF_PSDOR(:,IBL), PCVLC=PCLIM_PCVL(:,IBL), &
   & PCVHC=PCLIM_PCVH(:,IBL), PCURC=PCLIM_PCUR(:,IBL), &
   & PLAILC=PSURF_GSD_PLAILC(:,IBL), PLAIHC=PSURF_GSD_PLAIHC(:,IBL), &
   & PLAILI=PSURFL_PLAILI(:,IBL), PLAIHI=PSURFL_PLAIHI(:,IBL), &
   & PLAILCP=PSURF_GSD_PLAILC(:,IBL), PLAIHCP=PSURF_GSD_PLAIHC(:,IBL), &
   & PAVGPARC=PSURF_GSD_ZAVGPARC(:,IBL), &
   & PLSM=PCLIM_PLSM(:,IBL), PCI=PCLIM_PCI(:,IBL), PCIL=PSURF_PCIL(:,IBL), &
   & PCLAKE=PCLIM_PCLAKE(:,IBL), PHLICE=PSURF_GSP_PHLICE(:,IBL), &
   & PGEMU=PAUX_PGEMU(:,IBL), PSNM1M=PSURFL_PSNS(:,:,IBL), PWLM1M=PSURFL_PWL(:,IBL), &
   & PRSNM1M=PSURFL_PRSN(:,:,IBL), LESNICE=LESNICE, &
   & LDLAND=LLKEYS_LLLAND(:,IBL), LDSICE=LLKEYS_LLSICE(:,IBL), LDLICE=LLKEYS_LLLICE(:,IBL), &
   & LDLAKE=LLKEYS_LLLAKE(:,IBL), LDNH=LLKEYS_LLNH(:,IBL), LDOCN_KPP=LLKEYS_LLOCN_KPP(:,IBL), &
   & KTVL=PSURF_ITVL(:,IBL), KCO2TYP=PSURF_ICO2TYP(:,IBL), KTVH=PSURF_ITVH(:,IBL), KSOTY=PSURF_ISOTY(:,IBL), &
   & PCVL=PSURF_ZCVL(:,IBL), PCVH=PSURF_ZCVH(:,IBL), PCUR=PSURF_ZCUR(:,IBL), &
   & PLAIL=PSURFL_ZLAIL(:,IBL), PLAIH=PSURFL_ZLAIH(:,IBL), &
   & PLAILP=PSURF_ZLAILP(:,IBL), PLAIHP=PSURF_ZLAIHP(:,IBL), &
   & PAVGPAR=PSURF_ZAVGPAR(:,IBL), &
   & PWLMX=PSURFL_ZWLMX(:,IBL), PFRTI=PSURFL_ZFRTI(:,:,IBL), PCSN=PSURFL_ZCSN(:,IBL))
ENDDO

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_LOKI',1,ZHOOK_HANDLE)

END SUBROUTINE SURFBC_LAYER_LOKI

SUBROUTINE SURFBC_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PINTER, LLKEYS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NVHILO, NPOI
USE YOMDIM1S, ONLY : NPROMA
USE YOEPHY  , ONLY : LESNICE

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfbc.h"

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PINTER, LLKEYS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)

  CALL SURFBC(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, &
   & KLON=NPROMA, KTILES=NTILES, KLEVSN=NCSNEC, &
   & PSSDP2=PINTER%PSSDP2, PTVL=PCLIM%PTVL, PCO2TYP=PCLIM%PCO2TYP, &
   & PTVH=PCLIM%PTVH, PSOTY=PCLIM%PSOTY, PSDOR=ZSURF%PSDOR, PCVLC=PCLIM%PCVL, &
   & PCVHC=PCLIM%PCVH, PCURC=PCLIM%PCUR, &
   & PLAILC=ZSURF%GSD%PLAILC, PLAIHC=ZSURF%GSD%PLAIHC, &
   & PLAILI=PSURFL%PLAILI, PLAIHI=PSURFL%PLAIHI, &
   & PLAILCP=ZSURF%GSD%PLAILC, PLAIHCP=ZSURF%GSD%PLAIHC, &
   & PAVGPARC=ZSURF%GSD%ZAVGPARC, &
   & PLSM=PCLIM%PLSM, PCI=PCLIM%PCI, PCIL=ZSURF%PCIL, &
   & PCLAKE=PCLIM%PCLAKE, PHLICE=ZSURF%GSP%PHLICE, &
   & PGEMU=PAUX%PGEMU, PSNM1M=PSURFL%PSNS, PWLM1M=PSURFL%PWL, PRSNM1M=PSURFL%PRSN, &
   & LESNICE=LESNICE, &
   & LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDLICE=LLKEYS%LLLICE, &
   & LDLAKE=LLKEYS%LLLAKE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP, &
   & KTVL=ZSURF%ITVL, KCO2TYP=ZSURF%ICO2TYP, KTVH=ZSURF%ITVH, KSOTY=ZSURF%ISOTY, &
   & PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, PCUR=ZSURF%ZCUR, PLAIL=PSURFL%ZLAIL, &
   & PLAIH=PSURFL%ZLAIH, PLAILP=ZSURF%ZLAILP, PLAIHP=ZSURF%ZLAIHP, &
   & PAVGPAR=ZSURF%ZAVGPAR, &
   & PWLMX=PSURFL%ZWLMX, PFRTI=PSURFL%ZFRTI, PCSN=PSURFL%ZCSN)
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('SURFBC_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE SURFBC_LAYER_OPENMP

END MODULE SURFBC_LAYER_MOD
