MODULE VDFMAIN1S_LAYER_MOD
! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK

USE ECLAND_ATMO_TYPE_MOD,       ONLY : ATMO_TYPE
USE ECLAND_AUX_TYPE_MOD,        ONLY : AUX_TYPE, KEYS_LOCAL_TYPE
USE ECLAND_AUX_DIAG_TYPE_MOD,   ONLY : AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECLAND_CLIMATE_TYPE_MOD,    ONLY : CLIMATE_TYPE
USE ECLAND_DDH_TYPE_MOD,        ONLY : DDH_SURF_TYPE
USE ECLAND_FLUX_TYPE_MOD,       ONLY : FLUX_TYPE
USE ECLAND_GEMS_TYPE_MOD,       ONLY : GEMS_LOCAL_TYPE
USE ECLAND_INTERNAL_TYPE_MOD,   ONLY : INTERNAL_TYPE
USE ECLAND_SURFACE_TYPE_MOD,    ONLY : SURF_AND_MORE_TYPE
USE ECLAND_SURF_LOCAL_TYPE_MOD, ONLY : SURF_AND_MORE_LOCAL_TYPE

IMPLICIT NONE

CONTAINS

SUBROUTINE VDFMAIN1S_LAYER_PARALLEL(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS, ON_GPU)

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(AUX_DIAG_TYPE)             , INTENT(INOUT) :: PDIAG
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)           , INTENT(INOUT) :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)             , INTENT(INOUT) :: PDDHS
LOGICAL                         , INTENT(IN)    :: ON_GPU

IF (ON_GPU) THEN
  CALL VDFMAIN1S_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)
ELSE
  CALL VDFMAIN1S_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)
ENDIF

END SUBROUTINE VDFMAIN1S_LAYER_PARALLEL

SUBROUTINE VDFMAIN1S_LAYER_LOKI(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)
USE FIELD_ACCESS_MODULE, ONLY : SGET_DEVICE_DATA_RDWR
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, &
     &               NDHVTIS, NDHFTIS, NDHVCO2S, NDHFCO2S, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESNICE, LEVDIF, LEWARMSTART

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(AUX_DIAG_TYPE)             , INTENT(INOUT) :: PDIAG
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)           , INTENT(INOUT) :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)             , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA, JTILE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCHAR(:,:), PSURF_ZCHARHQ(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTOKES(:,:), PSURF_PVSTOKES(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PTAUOCX(:,:), PSURF_GSD_PTAUOCY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PPHIOC(:,:), PSURF_PWSEMEAN(:,:), PSURF_PWSFMEAN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTSAE1(:,:,:), PSURF_PWSAE1(:,:,:), PSURF_PTIAE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLE1(:,:), PSURF_PWLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSNSE1(:,:,:), PSURF_PTSNE1(:,:,:), PSURF_PRSNE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PWSNE1(:,:,:), PSURF_PASNE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZUCURR(:,:), PSURF_ZVCURR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLICEE1(:,:), PSURF_PTLMNWE1(:,:), PSURF_PTLWMLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PTLBOTE1(:,:), PSURF_PTLSFE1(:,:), PSURF_PHLICEE1(:,:), PSURF_PHLMLE1(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUOE1(:,:,:), PSURF_PVOE1(:,:,:), PSURF_PTOE1(:,:,:), PSURF_PSOE1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PUOC(:,:,:), PSURF_GSP_PVOC(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTRC(:,:), PSURF_PVSTRC(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PLAIE1(:,:,:), PSURF_PBSTRE1(:,:,:), PSURF_PBSTR2E1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PSDOR(:,:), PSURF_PCIL(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PCLIM_PLSM(:,:), PCLIM_PCUR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PAUX_PMU0M(:,:), PAUX_GELAT(:,:), PAUX_GELAM(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTSA(:,:,:), PSURF_GSP_PTL(:,:), PSURF_GSP_PASN(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTSN(:,:,:), PSURF_GSP_PWSA(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PSNS(:,:,:), PSURFL_PRSN(:,:,:), PSURFL_PWSN(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZEXDIAG(:,:,:)
LOGICAL, POINTER, CONTIGUOUS :: LLKEYS_LLSICE(:,:), LLKEYS_LLLAND(:,:)
INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: PSURF_ITVL(:,:), PSURF_ICO2TYP(:,:), PSURF_ITVH(:,:), PSURF_ISOTY(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZCVL(:,:), PSURF_ZCVH(:,:), PSURF_PFWET(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZLAIL(:,:), PSURFL_ZLAIH(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZLAILP(:,:), PSURF_ZLAIHP(:,:), PSURF_ZAVGPAR(:,:), PSURF_PISOP_EP(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PU(:,:), STATE_PV(:,:), STATE_PT(:,:), STATE_PQ(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: STATE_PAPRS(:,:,:), STATE_PGEOM1(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: GEMSL_PC(:,:,:), GEMSL_PCFLX(:,:,:), GEMSL_PZ0M(:,:), GEMSL_PZ0H(:,:), GEMSL_PBVOCFLUX(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFRSO(:,:,:), PFLUX_PFRTH(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZEMIS(:,:), PSURF_GSP_PTIA(:,:,:), PSURF_GSP_PHLICE(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSP_PTLICE(:,:), PSURF_GSP_PTLWML(:,:), PSURF_GSP_PSST(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRTI(:,:,:), PSURFL_ZALBTI(:,:,:), PSURFL_ZWLMX(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PINTER_PSSDP2(:,:,:), PINTER_PSSDP3(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDIAG_PVDIS(:,:), PDIAG_ZINV(:,:), PDIAG_PGUST(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PFTLHEV(:,:), PFLUX_PFTLHSB(:,:), PFLUX_PFWSB(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PEVAPTIU(:,:,:), PSURF_GSD_PU10M(:,:), PSURF_GSD_PV10M(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_GSD_PT2M(:,:), PSURF_GSD_PD2M(:,:), PSURF_GSD_PQ2M(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZFRSOTI(:,:,:), PSURFL_ZEVAPSNW(:,:), PSURFL_PZIDLWV(:,:), PSURFL_PSLRFLTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_ZTE(:,:), PSURF_ZQE(:,:), PSURF_ZVOM(:,:), PSURF_ZVOL(:,:), PSURF_ZTENC(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PUSTRTI(:,:,:), PSURF_PVSTRTI(:,:,:), PSURF_PAHFSTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PEVAPTI(:,:,:), PSURF_PTSKTI(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_PANDAYVT(:,:,:), PSURFL_PANFMVT(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PFLUX_PDIFTS(:,:,:), PFLUX_PDIFTQ(:,:,:), PFLUX_PSTRTU(:,:,:), PFLUX_PSTRTV(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURFL_ZKH(:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PAN(:,:), PSURF_PAG(:,:), PSURF_PRD(:,:), PSURF_PRSOIL_STR(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PSURF_PRECO(:,:), PSURF_PCO2FLUX(:,:), PSURF_PCH4FLUX(:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHTLS(:,:,:,:), PDDHS_PDHTSS(:,:,:,:), PDDHS_PDHTTS(:,:,:,:)
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PDDHS_PDHTIS(:,:,:,:), PDDHS_PDHCO2S(:,:,:,:), PDDHS_PDHBVOCS(:,:,:,:), PDDHS_PDHVEGS(:,:,:,:)

#include "surfws.h"
#include "vdfmain1s.intfb.h"

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_LOKI',0,ZHOOK_HANDLE)

CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCHAR, PSURF%F_ZCHAR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCHARHQ, PSURF%F_ZCHARHQ)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTOKES, PSURF%F_PUSTOKES)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTOKES, PSURF%F_PVSTOKES)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTAUOCX, PSURF%GSD%F_PTAUOCX)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PTAUOCY, PSURF%GSD%F_PTAUOCY)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PPHIOC, PSURF%F_PPHIOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSEMEAN, PSURF%F_PWSEMEAN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSFMEAN, PSURF%F_PWSFMEAN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTSAE1, PSURF%F_PTSAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSAE1, PSURF%F_PWSAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTIAE1, PSURF%F_PTIAE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLE1, PSURF%F_PTLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWLE1, PSURF%F_PWLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSNSE1, PSURF%F_PSNSE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTSNE1, PSURF%F_PTSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRSNE1, PSURF%F_PRSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PWSNE1, PSURF%F_PWSNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PASNE1, PSURF%F_PASNE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZUCURR, PSURF%F_ZUCURR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZVCURR, PSURF%F_ZVCURR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLICEE1, PSURF%F_PTLICEE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLMNWE1, PSURF%F_PTLMNWE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLWMLE1, PSURF%F_PTLWMLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLBOTE1, PSURF%F_PTLBOTE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTLSFE1, PSURF%F_PTLSFE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PHLICEE1, PSURF%F_PHLICEE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PHLMLE1, PSURF%F_PHLMLE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUOE1, PSURF%F_PUOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVOE1, PSURF%F_PVOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTOE1, PSURF%F_PTOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSOE1, PSURF%F_PSOE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PUOC, PSURF%GSP%F_PUOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PVOC, PSURF%GSP%F_PVOC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTRC, PSURF%F_PUSTRC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTRC, PSURF%F_PVSTRC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PLAIE1, PSURF%F_PLAIE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBSTRE1, PSURF%F_PBSTRE1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PBSTR2E1, PSURF%F_PBSTR2E1)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PSDOR, PSURF%F_PSDOR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PCIL, PSURF%F_PCIL)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PLSM, PCLIM%F_PLSM)
CALL SGET_DEVICE_DATA_RDWR(PCLIM_PCUR, PCLIM%F_PCUR)
CALL SGET_DEVICE_DATA_RDWR(PAUX_PMU0M, PAUX%F_PMU0M)
CALL SGET_DEVICE_DATA_RDWR(PAUX_GELAT, PAUX%F_GELAT)
CALL SGET_DEVICE_DATA_RDWR(PAUX_GELAM, PAUX%F_GELAM)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTSA, PSURF%GSP%F_PTSA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTL, PSURF%GSP%F_PTL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PASN, PSURF%GSP%F_PASN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTSN, PSURF%GSP%F_PTSN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PWSA, PSURF%GSP%F_PWSA)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PSNS, PSURFL%F_PSNS)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PRSN, PSURFL%F_PRSN)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PWSN, PSURFL%F_PWSN)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZEXDIAG, PSURFL%F_ZEXDIAG)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLSICE, LLKEYS%F_LLSICE)
CALL SGET_DEVICE_DATA_RDWR(LLKEYS_LLLAND, LLKEYS%F_LLLAND)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVL, PSURF%F_ITVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ICO2TYP, PSURF%F_ICO2TYP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ITVH, PSURF%F_ITVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ISOTY, PSURF%F_ISOTY)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVL, PSURF%F_ZCVL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZCVH, PSURF%F_ZCVH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PFWET, PSURF%F_PFWET)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIL, PSURFL%F_ZLAIL)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZLAIH, PSURFL%F_ZLAIH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZLAILP, PSURF%F_ZLAILP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZLAIHP, PSURF%F_ZLAIHP)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZAVGPAR, PSURF%F_ZAVGPAR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PISOP_EP, PSURF%F_PISOP_EP)
CALL SGET_DEVICE_DATA_RDWR(STATE_PU, STATE%F_PU)
CALL SGET_DEVICE_DATA_RDWR(STATE_PV, STATE%F_PV)
CALL SGET_DEVICE_DATA_RDWR(STATE_PT, STATE%F_PT)
CALL SGET_DEVICE_DATA_RDWR(STATE_PQ, STATE%F_PQ)
CALL SGET_DEVICE_DATA_RDWR(STATE_PAPRS, STATE%F_PAPRS)
CALL SGET_DEVICE_DATA_RDWR(STATE_PGEOM1, STATE%F_PGEOM1)
CALL SGET_DEVICE_DATA_RDWR(GEMSL_PC, GEMSL%F_PC)
CALL SGET_DEVICE_DATA_RDWR(GEMSL_PCFLX, GEMSL%F_PCFLX)
CALL SGET_DEVICE_DATA_RDWR(GEMSL_PZ0M, GEMSL%F_PZ0M)
CALL SGET_DEVICE_DATA_RDWR(GEMSL_PZ0H, GEMSL%F_PZ0H)
CALL SGET_DEVICE_DATA_RDWR(GEMSL_PBVOCFLUX, GEMSL%F_PBVOCFLUX)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFRSO, PFLUX%F_PFRSO)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFRTH, PFLUX%F_PFRTH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZEMIS, PSURF%F_ZEMIS)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTIA, PSURF%GSP%F_PTIA)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PHLICE, PSURF%GSP%F_PHLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLICE, PSURF%GSP%F_PTLICE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PTLWML, PSURF%GSP%F_PTLWML)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSP_PSST, PSURF%GSP%F_PSST)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRTI, PSURFL%F_ZFRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZALBTI, PSURFL%F_ZALBTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZWLMX, PSURFL%F_ZWLMX)
CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP2, PINTER%F_PSSDP2)
CALL SGET_DEVICE_DATA_RDWR(PINTER_PSSDP3, PINTER%F_PSSDP3)
CALL SGET_DEVICE_DATA_RDWR(PDIAG_PVDIS, PDIAG%F_PVDIS)
CALL SGET_DEVICE_DATA_RDWR(PDIAG_ZINV, PDIAG%F_ZINV)
CALL SGET_DEVICE_DATA_RDWR(PDIAG_PGUST, PDIAG%F_PGUST)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFTLHEV, PFLUX%F_PFTLHEV)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFTLHSB, PFLUX%F_PFTLHSB)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PFWSB, PFLUX%F_PFWSB)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PEVAPTIU, PSURF%GSD%F_PEVAPTIU)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PU10M, PSURF%GSD%F_PU10M)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PV10M, PSURF%GSD%F_PV10M)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PT2M, PSURF%GSD%F_PT2M)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PD2M, PSURF%GSD%F_PD2M)
CALL SGET_DEVICE_DATA_RDWR(PSURF_GSD_PQ2M, PSURF%GSD%F_PQ2M)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZFRSOTI, PSURFL%F_ZFRSOTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZEVAPSNW, PSURFL%F_ZEVAPSNW)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PZIDLWV, PSURFL%F_PZIDLWV)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PSLRFLTI, PSURFL%F_PSLRFLTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZTE, PSURF%F_ZTE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZQE, PSURF%F_ZQE)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZVOM, PSURF%F_ZVOM)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZVOL, PSURF%F_ZVOL)
CALL SGET_DEVICE_DATA_RDWR(PSURF_ZTENC, PSURF%F_ZTENC)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PUSTRTI, PSURF%F_PUSTRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PVSTRTI, PSURF%F_PVSTRTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PAHFSTI, PSURF%F_PAHFSTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PEVAPTI, PSURF%F_PEVAPTI)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PTSKTI, PSURF%F_PTSKTI)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PANDAYVT, PSURFL%F_PANDAYVT)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_PANFMVT, PSURFL%F_PANFMVT)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PDIFTS, PFLUX%F_PDIFTS)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PDIFTQ, PFLUX%F_PDIFTQ)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PSTRTU, PFLUX%F_PSTRTU)
CALL SGET_DEVICE_DATA_RDWR(PFLUX_PSTRTV, PFLUX%F_PSTRTV)
CALL SGET_DEVICE_DATA_RDWR(PSURFL_ZKH, PSURFL%F_ZKH)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PAN, PSURF%F_PAN)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PAG, PSURF%F_PAG)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRD, PSURF%F_PRD)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRSOIL_STR, PSURF%F_PRSOIL_STR)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PRECO, PSURF%F_PRECO)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PCO2FLUX, PSURF%F_PCO2FLUX)
CALL SGET_DEVICE_DATA_RDWR(PSURF_PCH4FLUX, PSURF%F_PCH4FLUX)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTLS, PDDHS%F_PDHTLS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTSS, PDDHS%F_PDHTSS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTTS, PDDHS%F_PDHTTS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHTIS, PDDHS%F_PDHTIS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHCO2S, PDDHS%F_PDHCO2S)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHBVOCS, PDDHS%F_PDHBVOCS)
CALL SGET_DEVICE_DATA_RDWR(PDDHS_PDHVEGS, PDDHS%F_PDHVEGS)

IF ( (NSTEP==NSTART) .AND. (LEWARMSTART) ) THEN
  CALL VDFMAIN1S_LAYER_WARMSTART(YSURF=YSURF, KPOI=NPOI, KPROMA=NPROMA, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES, &
       & PSDOR=PSURF_PSDOR, LDSICE=LLKEYS_LLSICE, PLSM=PCLIM_PLSM, PCIL=PSURF_PCIL, PFRTI=PSURFL_ZFRTI, &
       & PMU0=PAUX_PMU0M, PTSAM1M=PSURF_GSP_PTSA, PTSKIN=PSURF_GSP_PTL, PALBSN=PSURF_GSP_PASN, &
       & PTSNM1M=PSURF_GSP_PTSN, PSNM1M=PSURFL_PSNS, PRSNM1M=PSURFL_PRSN, PWSNM1M=PSURFL_PWSN)
ENDIF

DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  PSURF_ZCHAR(KIDIA:KFDIA,IBL)=0.018_JPRB
  PSURF_ZCHARHQ(KIDIA:KFDIA,IBL)=0.006_JPRB
  PSURF_PUSTOKES(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PVSTOKES(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_GSD_PTAUOCX(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_GSD_PTAUOCY(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PPHIOC(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PWSEMEAN(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PWSFMEAN(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTSAE1(KIDIA:KFDIA,1:NCSS,IBL)=0.0_JPRB
  PSURF_PWSAE1(KIDIA:KFDIA,1:NCSS,IBL)=0.0_JPRB
  PSURF_PTIAE1(KIDIA:KFDIA,1:NCSS,IBL)=0.0_JPRB
  PSURF_PTLE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PWLE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PSNSE1(KIDIA:KFDIA,1:NCSNEC,IBL)=0.0_JPRB
  PSURF_PTSNE1(KIDIA:KFDIA,1:NCSNEC,IBL)=0.0_JPRB
  PSURF_PRSNE1(KIDIA:KFDIA,1:NCSNEC,IBL)=0.0_JPRB
  PSURF_PWSNE1(KIDIA:KFDIA,1:NCSNEC,IBL)=0.0_JPRB
  PSURF_PASNE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_ZUCURR(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_ZVCURR(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTLICEE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTLMNWE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTLWMLE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTLBOTE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PTLSFE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PHLICEE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PHLMLE1(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PUOE1(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_PVOE1(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_PTOE1(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_PSOE1(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_GSP_PUOC(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_GSP_PVOC(KIDIA:KFDIA,1:NCOM+1,IBL)=0.0_JPRB
  PSURF_PUSTRC(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PVSTRC(KIDIA:KFDIA,IBL)=0.0_JPRB
  PSURF_PLAIE1(KIDIA:KFDIA,1:NVHILO,IBL)=0.0_JPRB
  PSURF_PBSTRE1(KIDIA:KFDIA,1:NVHILO,IBL)=0.0_JPRB
  PSURF_PBSTR2E1(KIDIA:KFDIA,1:NVHILO,IBL)=0.0_JPRB

  PSURFL_ZEXDIAG(KIDIA:KFDIA,11,IBL)=PAUX_GELAT(KIDIA:KFDIA,IBL)
  PSURFL_ZEXDIAG(KIDIA:KFDIA,12,IBL)=PAUX_GELAM(KIDIA:KFDIA,IBL)

  IF ( LEVDIF ) THEN
    CALL VDFMAIN1S ( &
     & YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA, KLEV=NLEV, KLEVS=NCSS, &
     & KSTEP=NSTEP, KTILES=NTILES, KVTYPES=NVHILO, KDIAG=12_JPIM, &
     & KTRAC=NTRAC, KLEVSN=NCSNEC, KLEVI=NLEVI, LDLAND=LLKEYS_LLLAND(:,IBL), &
     & KDHVTLS=NDHVTLS, KDHFTLS=NDHFTLS, KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVCO2S=NDHVCO2S, KDHFCO2S=NDHFCO2S, KDHVBVOCS=NDHVBVOCS, KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & LESNICE=LESNICE, &
     & PMU0=PAUX_PMU0M(:,IBL), PTSPHY=TDT, &
     & KTVL=PSURF_ITVL(:,IBL), KCO2TYP=PSURF_ICO2TYP(:,IBL), KTVH=PSURF_ITVH(:,IBL), &
     & PCVL=PSURF_ZCVL(:,IBL), PCVH=PSURF_ZCVH(:,IBL), PCUR=PCLIM_PCUR(:,IBL), &
     & PFWET=PSURF_PFWET(:,IBL), PLAT=PAUX_GELAT(:,IBL), PLAIL=PSURFL_ZLAIL(:,IBL), PLAIH=PSURFL_ZLAIH(:,IBL), &
     & PLAILP=PSURF_ZLAILP(:,IBL), PLAIHP=PSURF_ZLAIHP(:,IBL), PAVGPAR=PSURF_ZAVGPAR(:,IBL), PISOP_EP=PSURF_PISOP_EP(:,IBL), &
     & PCIL=PSURF_PCIL(:,IBL), PSNM1M=PSURFL_PSNS(:,:,IBL), PRSNM1M=PSURFL_PRSN(:,:,IBL), &
     & PUM1=STATE_PU(:,IBL), PVM1=STATE_PV(:,IBL), PTM1=STATE_PT(:,IBL), PQM1=STATE_PQ(:,IBL), PCM1=GEMSL_PC(:,:,IBL), &
     & PAPHM1=STATE_PAPRS(:,:,IBL), PGEOM1=STATE_PGEOM1(:,:,IBL), &
     & PTSKM1M=PSURF_GSP_PTL(:,IBL), PTSAM1M=PSURF_GSP_PTSA(:,:,IBL), PWSAM1M=PSURF_GSP_PWSA(:,:,IBL), &
     & PSSRFL=PFLUX_PFRSO(:,NLEV,IBL), PSLRFL=PFLUX_PFRTH(:,NLEV,IBL), PEMIS=PSURF_ZEMIS(:,IBL), &
     & PTSN=PSURF_GSP_PTSN(:,:,IBL), PTICE=PSURF_GSP_PTIA(:,:,IBL), &
     & PHLICE=PSURF_GSP_PHLICE(:,IBL), PTLICE=PSURF_GSP_PTLICE(:,IBL), PTLWML=PSURF_GSP_PTLWML(:,IBL), &
     & PSST=PSURF_GSP_PSST(:,IBL), KSOTY=PSURF_ISOTY(:,IBL), PFRTI=PSURFL_ZFRTI(:,:,IBL), &
     & PALBTI=PSURFL_ZALBTI(:,:,IBL), PWLMX=PSURFL_ZWLMX(:,IBL), &
     & PCHAR=PSURF_ZCHAR(:,IBL), PCHARHQ=PSURF_ZCHARHQ(:,IBL), PUCURR=PSURF_ZUCURR(:,IBL), PVCURR=PSURF_ZVCURR(:,IBL), &
     & PTSKRAD=PSURF_GSP_PTL(:,IBL), PCFLX=GEMSL_PCFLX(:,:,IBL), &
     & PSSDP2=PINTER_PSSDP2(:,:,IBL), PSSDP3=PINTER_PSSDP3(:,:,:,IBL), PZ0M=GEMSL_PZ0M(:,IBL), PZ0H=GEMSL_PZ0H(:,IBL), &
     & PVDIS=PDIAG_PVDIS(:,IBL), PAHFLEV=PFLUX_PFTLHEV(:,IBL), PAHFLSB=PFLUX_PFTLHSB(:,IBL), PFWSB=PFLUX_PFWSB(:,IBL), &
     & PU10M=PSURF_GSD_PU10M(:,IBL), PV10M=PSURF_GSD_PV10M(:,IBL), PT2M=PSURF_GSD_PT2M(:,IBL), &
     & PD2M=PSURF_GSD_PD2M(:,IBL), PQ2M=PSURF_GSD_PQ2M(:,IBL), PZINV=PDIAG_ZINV(:,IBL), &
     & PSSRFLTI=PSURFL_ZFRSOTI(:,:,IBL), PEVAPSNW=PSURFL_ZEVAPSNW(:,IBL), PEXDIAG=PSURFL_ZEXDIAG(:,:,IBL), &
     & PGUST=PDIAG_PGUST(:,IBL), PZIDLWV=PSURFL_PZIDLWV(:,IBL), PTE=PSURF_ZTE(:,IBL), PQE=PSURF_ZQE(:,IBL), &
     & PVOM=PSURF_ZVOM(:,IBL), PVOL=PSURF_ZVOL(:,IBL), PTENC=PSURF_ZTENC(:,:,IBL), PTSKE1=PSURF_PTLE1(:,IBL), &
     & PUSTRTI=PSURF_PUSTRTI(:,:,IBL), PVSTRTI=PSURF_PVSTRTI(:,:,IBL), PAHFSTI=PSURF_PAHFSTI(:,:,IBL), &
     & PEVAPTI=PSURF_PEVAPTI(:,:,IBL), PTSKTI=PSURF_PTSKTI(:,:,IBL), PSLRFLTI=PSURFL_PSLRFLTI(:,:,IBL), &
     & PANDAYVT=PSURFL_PANDAYVT(:,:,IBL), PANFMVT=PSURFL_PANFMVT(:,:,IBL), &
     & PEVAPTIU=PSURF_GSD_PEVAPTIU(:,:,IBL), PDIFTS=PFLUX_PDIFTS(:,:,IBL), PDIFTQ=PFLUX_PDIFTQ(:,:,IBL), &
     & PSTRTU=PFLUX_PSTRTU(:,:,IBL), PSTRTV=PFLUX_PSTRTV(:,:,IBL), PKH=PSURFL_ZKH(:,:,IBL), &
     & PAN=PSURF_PAN(:,IBL), PAG=PSURF_PAG(:,IBL), PRD=PSURF_PRD(:,IBL), PRSOIL_STR=PSURF_PRSOIL_STR(:,IBL), &
     & PRECO=PSURF_PRECO(:,IBL), PCO2FLUX=PSURF_PCO2FLUX(:,IBL), PCH4FLUX=PSURF_PCH4FLUX(:,IBL), &
     & PBVOCFLUX=GEMSL_PBVOCFLUX(:,:,IBL), &
     & PDHTLS=PDDHS_PDHTLS(:,:,:,IBL), PDHTSS=PDDHS_PDHTSS(:,:,:,IBL), PDHTTS=PDDHS_PDHTTS(:,:,:,IBL), &
     & PDHTIS=PDDHS_PDHTIS(:,:,:,IBL), PDHCO2S=PDDHS_PDHCO2S(:,:,:,IBL), &
     & PDHBVOCS=PDDHS_PDHBVOCS(:,:,:,IBL), PDHVEGS=PDDHS_PDHVEGS(:,:,:,IBL))
  ELSE
    PDIAG_PVDIS(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFTLHEV(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFTLHSB(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PFWSB(KIDIA:KFDIA,IBL)=0._JPRB
    PSURFL_ZEVAPSNW(KIDIA:KFDIA,IBL)=0._JPRB
    PFLUX_PDIFTQ(KIDIA:KFDIA,1:NCSS,IBL)=0._JPRB
    PFLUX_PDIFTS(KIDIA:KFDIA,1:NCSS,IBL)=0._JPRB
    PFLUX_PSTRTU(KIDIA:KFDIA,1:NCSS,IBL)=0._JPRB
    PFLUX_PSTRTV(KIDIA:KFDIA,1:NCSS,IBL)=0._JPRB
    DO JTILE=1,NTILES
      PSURFL_ZFRSOTI(KIDIA:KFDIA,JTILE,IBL)=PFLUX_PFRSO(KIDIA:KFDIA,NLEV,IBL)
      PSURF_PUSTRTI(KIDIA:KFDIA,JTILE,IBL)=0._JPRB
      PSURF_PVSTRTI(KIDIA:KFDIA,JTILE,IBL)=0._JPRB
      PSURF_PAHFSTI(KIDIA:KFDIA,JTILE,IBL)=0._JPRB
      PSURF_PEVAPTI(KIDIA:KFDIA,JTILE,IBL)=0._JPRB
      PSURF_PTSKTI(KIDIA:KFDIA,JTILE,IBL)=PSURF_GSP_PTL(KIDIA:KFDIA,IBL)
    ENDDO
  ENDIF
ENDDO

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_LOKI',1,ZHOOK_HANDLE)

END SUBROUTINE VDFMAIN1S_LAYER_LOKI

SUBROUTINE VDFMAIN1S_LAYER_WARMSTART(YSURF, KPOI, KPROMA, KLEVS, KLEVSN, KTILES, &
     & PSDOR, LDSICE, PLSM, PCIL, PFRTI, PMU0, PTSAM1M, PTSKIN, PALBSN, &
     & PTSNM1M, PSNM1M, PRSNM1M, PWSNM1M)
USE YOS_SURF, ONLY : TSURF

TYPE(TSURF)       , INTENT(IN)    :: YSURF
INTEGER(KIND=JPIM), INTENT(IN)    :: KPOI, KPROMA, KLEVS, KLEVSN, KTILES
REAL(KIND=JPRB)   , INTENT(IN)    :: PSDOR(:,:), PLSM(:,:), PCIL(:,:), PMU0(:,:)
LOGICAL           , INTENT(IN)    :: LDSICE(:,:)
REAL(KIND=JPRB)   , INTENT(IN)    :: PFRTI(:,:,:), PTSAM1M(:,:,:), PTSKIN(:,:), PALBSN(:,:)
REAL(KIND=JPRB)   , INTENT(INOUT) :: PTSNM1M(:,:,:), PSNM1M(:,:,:), PRSNM1M(:,:,:), PWSNM1M(:,:,:)

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA

#include "surfws.h"

DO IST=1,KPOI,KPROMA
  IEND = MIN(IST+KPROMA-1,KPOI)
  IBL = (IST-1)/KPROMA+1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL SURFWS(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, KLON=KPROMA, KLEVS=KLEVS, KLEVSN=KLEVSN, KTILES=KTILES &
       &     ,PSDOR=PSDOR(:,IBL), LDSICE=LDSICE(:,IBL) &
       &     ,PLSM=PLSM(:,IBL), PCIL=PCIL(:,IBL), PFRTI=PFRTI(:,:,IBL), PMU0=PMU0(:,IBL) &
       &     ,PTSAM1M=PTSAM1M(:,:,IBL), PTSKIN=PTSKIN(:,IBL), PALBSN=PALBSN(:,IBL) &
       &     ,PTSNM1M=PTSNM1M(:,:,IBL), PSNM1M=PSNM1M(:,:,IBL), PRSNM1M=PRSNM1M(:,:,IBL), &
       &      PWSNM1M=PWSNM1M(:,:,IBL))
ENDDO

END SUBROUTINE VDFMAIN1S_LAYER_WARMSTART

SUBROUTINE VDFMAIN1S_LAYER_OPENMP(PSURF, PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)
USE YOMDPHY , ONLY : YSURF, NCOM, NCSNEC, NCSS, NTILES, NTRAC, NVHILO, NPOI, NLEV
USE YOMCDH1S, ONLY : NLEVI, NDHVTLS, NDHFTLS, NDHVTSS, NDHFTSS, NDHVTTS, NDHFTTS, &
     &               NDHVTIS, NDHFTIS, NDHVCO2S, NDHFCO2S, NDHVBVOCS, NDHVVEGS, NDHFVEGS
USE YOMCT01S, ONLY : NSTART
USE YOMDIM1S, ONLY : NPROMA
USE YOMDYN1S, ONLY : NSTEP, TDT
USE YOEPHY  , ONLY : LESNICE, LEVDIF, LEWARMSTART

TYPE(SURF_AND_MORE_TYPE)        , INTENT(INOUT) :: PSURF
TYPE(SURF_AND_MORE_LOCAL_TYPE)  , INTENT(INOUT) :: PSURFL
TYPE(CLIMATE_TYPE)              , INTENT(INOUT) :: PCLIM
TYPE(AUX_TYPE)                  , INTENT(INOUT) :: PAUX
TYPE(AUX_DIAG_LOCAL_TYPE)       , INTENT(INOUT) :: PAUXL
TYPE(AUX_DIAG_TYPE)             , INTENT(INOUT) :: PDIAG
TYPE(FLUX_TYPE)                 , INTENT(INOUT) :: PFLUX
TYPE(INTERNAL_TYPE)             , INTENT(INOUT) :: PINTER
TYPE(ATMO_TYPE)                 , INTENT(INOUT) :: STATE
TYPE(GEMS_LOCAL_TYPE)           , INTENT(INOUT) :: GEMSL
TYPE(KEYS_LOCAL_TYPE)           , INTENT(INOUT) :: LLKEYS
TYPE(DDH_SURF_TYPE)             , INTENT(INOUT) :: PDDHS

INTEGER(KIND=JPIM) :: IST, IEND, IBL, KIDIA, KFDIA, JTILE
TYPE(SURF_AND_MORE_TYPE) :: ZSURF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "surfws.h"
#include "vdfmain1s.intfb.h"

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_OPENMP',0,ZHOOK_HANDLE)

!$OMP PARALLEL &
!$OMP PRIVATE(IST, IEND, IBL, KIDIA, KFDIA, JTILE, ZSURF) &
!$OMP FIRSTPRIVATE(PSURFL, PCLIM, PAUX, PAUXL, PDIAG, PFLUX, PINTER, STATE, GEMSL, LLKEYS, PDDHS)

ZSURF=PSURF

!$OMP DO SCHEDULE(DYNAMIC,1)
DO IST = 1, NPOI, NPROMA
  IEND = MIN(IST+NPROMA-1,NPOI)
  IBL = (IST-1)/NPROMA + 1
  KIDIA = 1
  KFDIA = IEND-IST+1

  CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL, NCSNEC=NCSNEC, NCSS=NCSS, NCOM=NCOM, NVHILO=NVHILO)
  CALL ZSURF%GSD%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL ZSURF%GSP%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PCLIM%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PINTER%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL STATE%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL GEMSL%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL LLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
  CALL PDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)

!*      1.3   GLOBAL AUXILLIARY VARIABLES
  ZSURF%ZCHAR(KIDIA:KFDIA)  =0.018_JPRB
  ZSURF%ZCHARHQ(KIDIA:KFDIA)=0.006_JPRB

!*      1.3a   GLOBAL OCEAN TEMPORALY SET TO ZERO (to check with PJ)
  ZSURF%PUSTOKES(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PVSTOKES(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%GSD%PTAUOCX(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%GSD%PTAUOCY(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PPHIOC(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWSEMEAN(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWSFMEAN(KIDIA:KFDIA)=0.0_JPRB

!*       1.4  SET SURFACE TENDENCIES TO ZERO
  ZSURF%PTSAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PWSAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PTIAE1(KIDIA:KFDIA,1:NCSS)=0.0_JPRB
  ZSURF%PTLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PWLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PSNSE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PTSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PRSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PWSNE1(KIDIA:KFDIA,1:NCSNEC)=0.0_JPRB
  ZSURF%PASNE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%ZUCURR(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%ZVCURR(KIDIA:KFDIA)=0.0_JPRB

!* FLAKE
  ZSURF%PTLICEE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLMNWE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLWMLE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLBOTE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PTLSFE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PHLICEE1(KIDIA:KFDIA)=0.0_JPRB
  ZSURF%PHLMLE1(KIDIA:KFDIA)=0.0_JPRB

  ZSURF%PUOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PVOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PTOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%PSOE1(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB !KPP
  ZSURF%GSP%PUOC(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB  !KPP
  ZSURF%GSP%PVOC(KIDIA:KFDIA,1:NCOM+1)=0.0_JPRB  !KPP
  ZSURF%PUSTRC(KIDIA:KFDIA)=0.0_JPRB          !KPP
  ZSURF%PVSTRC(KIDIA:KFDIA)=0.0_JPRB          !KPP

!* CTESSEL
  ZSURF%PLAIE1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB
  ZSURF%PBSTRE1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB
  ZSURF%PBSTR2E1(KIDIA:KFDIA,1:NVHILO)=0.0_JPRB

  IF ( (NSTEP==NSTART) .AND. (LEWARMSTART) )  THEN
    CALL SURFWS(YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA, KLEVS=NCSS, KLEVSN=NCSNEC, KTILES=NTILES &
         &     ,PSDOR=ZSURF%PSDOR, LDSICE=LLKEYS%LLSICE &
         &     ,PLSM=PCLIM%PLSM, PCIL=ZSURF%PCIL, PFRTI=PSURFL%ZFRTI, PMU0=PAUX%PMU0M &
         &     ,PTSAM1M=ZSURF%GSP%PTSA, PTSKIN=ZSURF%GSP%PTL, PALBSN=ZSURF%GSP%PASN &
         &     ,PTSNM1M=ZSURF%GSP%PTSN, PSNM1M=PSURFL%PSNS, PRSNM1M=PSURFL%PRSN, PWSNM1M=PSURFL%PWSN)
  ENDIF

  PSURFL%ZEXDIAG(KIDIA:KFDIA,11)=PAUX%GELAT(KIDIA:KFDIA) ! Latitude
  PSURFL%ZEXDIAG(KIDIA:KFDIA,12)=PAUX%GELAM(KIDIA:KFDIA) ! Longitude

  IF ( LEVDIF ) THEN
    CALL VDFMAIN1S ( &
     & YSURF=YSURF, KIDIA=KIDIA, KFDIA=KFDIA, KLON=NPROMA, KLEV=NLEV, KLEVS=NCSS, &
     & KSTEP=NSTEP, KTILES=NTILES, KVTYPES=NVHILO, KDIAG=12_JPIM, &
     & KTRAC=NTRAC, KLEVSN=NCSNEC, KLEVI=NLEVI, LDLAND=LLKEYS%LLLAND, &
     & KDHVTLS=NDHVTLS, KDHFTLS=NDHFTLS, KDHVTSS=NDHVTSS, KDHFTSS=NDHFTSS, &
     & KDHVTTS=NDHVTTS, KDHFTTS=NDHFTTS, KDHVTIS=NDHVTIS, KDHFTIS=NDHFTIS, &
     & KDHVCO2S=NDHVCO2S, KDHFCO2S=NDHFCO2S, KDHVBVOCS=NDHVBVOCS, KDHVVEGS=NDHVVEGS, KDHFVEGS=NDHFVEGS, &
     & LESNICE=LESNICE, &
     & PMU0=PAUX%PMU0M, &
     & PTSPHY=TDT, &
     & KTVL=ZSURF%ITVL, KCO2TYP=ZSURF%ICO2TYP, KTVH=ZSURF%ITVH, PCVL=ZSURF%ZCVL, PCVH=ZSURF%ZCVH, &
     & PCUR=PCLIM%PCUR, PFWET=ZSURF%PFWET, PLAT=PAUX%GELAT, PLAIL=PSURFL%ZLAIL, PLAIH=PSURFL%ZLAIH, &
     & PLAILP=ZSURF%ZLAILP, PLAIHP=ZSURF%ZLAIHP, PAVGPAR=ZSURF%ZAVGPAR, PISOP_EP=ZSURF%PISOP_EP, &
     & PCIL=ZSURF%PCIL, &
     & PSNM1M=PSURFL%PSNS, PRSNM1M=PSURFL%PRSN, &
     & PUM1=STATE%PU, PVM1=STATE%PV, PTM1=STATE%PT, &
     & PQM1=STATE%PQ, PCM1=GEMSL%PC, &
     & PAPHM1=STATE%PAPRS, PGEOM1=STATE%PGEOM1, &
     & PTSKM1M=ZSURF%GSP%PTL ,PTSAM1M=ZSURF%GSP%PTSA,PWSAM1M=ZSURF%GSP%PWSA, &
     & PSSRFL=PFLUX%PFRSO(:,NLEV),PSLRFL=PFLUX%PFRTH(:,NLEV),PEMIS=ZSURF%ZEMIS, &
     & PTSN=ZSURF%GSP%PTSN, PTICE=ZSURF%GSP%PTIA, &
     & PHLICE=ZSURF%GSP%PHLICE, PTLICE=ZSURF%GSP%PTLICE, PTLWML=ZSURF%GSP%PTLWML, &
     & PSST=ZSURF%GSP%PSST, KSOTY=ZSURF%ISOTY, PFRTI=PSURFL%ZFRTI, PALBTI=PSURFL%ZALBTI, PWLMX=PSURFL%ZWLMX, &
     & PCHAR=ZSURF%ZCHAR, PCHARHQ=ZSURF%ZCHARHQ, PUCURR=ZSURF%ZUCURR, PVCURR=ZSURF%ZVCURR, &
     & PTSKRAD=ZSURF%GSP%PTL, &
     & PCFLX=GEMSL%PCFLX, &
     & PSSDP2=PINTER%PSSDP2, PSSDP3=PINTER%PSSDP3, &
     & PZ0M=GEMSL%PZ0M, PZ0H=GEMSL%PZ0H, &
     & PVDIS=PDIAG%PVDIS, PAHFLEV=PFLUX%PFTLHEV, &
     & PAHFLSB=PFLUX%PFTLHSB, &
     & PFWSB=PFLUX%PFWSB, &
     & PU10M=ZSURF%GSD%PU10M, PV10M=ZSURF%GSD%PV10M, &
     & PT2M=ZSURF%GSD%PT2M, PD2M=ZSURF%GSD%PD2M, &
     & PQ2M=ZSURF%GSD%PQ2M, PZINV=PDIAG%ZINV, &
     & PSSRFLTI=PSURFL%ZFRSOTI, PEVAPSNW=PSURFL%ZEVAPSNW, &
     & PEXDIAG=PSURFL%ZEXDIAG, PGUST=PDIAG%PGUST, PZIDLWV=PSURFL%PZIDLWV, &
     & PTE=ZSURF%ZTE, PQE=ZSURF%ZQE, PVOM=ZSURF%ZVOM, &
     & PVOL=ZSURF%ZVOL, PTENC=ZSURF%ZTENC, PTSKE1=ZSURF%PTLE1, &
     & PUSTRTI=ZSURF%PUSTRTI, PVSTRTI=ZSURF%PVSTRTI, PAHFSTI=ZSURF%PAHFSTI, &
     & PEVAPTI=ZSURF%PEVAPTI, PTSKTI=ZSURF%PTSKTI, PSLRFLTI=PSURFL%PSLRFLTI, &
     & PANDAYVT=PSURFL%PANDAYVT, PANFMVT=PSURFL%PANFMVT, &
     & PEVAPTIU=ZSURF%GSD%PEVAPTIU, PDIFTS=PFLUX%PDIFTS, PDIFTQ=PFLUX%PDIFTQ, &
     & PSTRTU=PFLUX%PSTRTU, PSTRTV=PFLUX%PSTRTV, PKH=PSURFL%ZKH, &
     & PAN=ZSURF%PAN, PAG=ZSURF%PAG, PRD=ZSURF%PRD, PRSOIL_STR=ZSURF%PRSOIL_STR, &
     & PRECO=ZSURF%PRECO, PCO2FLUX=ZSURF%PCO2FLUX, PCH4FLUX=ZSURF%PCH4FLUX, &
     & PBVOCFLUX=GEMSL%PBVOCFLUX, &
     & PDHTLS=PDDHS%PDHTLS, PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, &
     & PDHTIS=PDDHS%PDHTIS, PDHCO2S=PDDHS%PDHCO2S, PDHBVOCS=PDDHS%PDHBVOCS, PDHVEGS=PDDHS%PDHVEGS)
  ELSE
    PDIAG%PVDIS(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFTLHEV(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFTLHSB(KIDIA:KFDIA)=0._JPRB
    PFLUX%PFWSB(KIDIA:KFDIA)=0._JPRB
    PSURFL%ZEVAPSNW(KIDIA:KFDIA)=0._JPRB
    PFLUX%PDIFTQ(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PDIFTS(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PSTRTU(KIDIA:KFDIA,1:NCSS)=0._JPRB
    PFLUX%PSTRTV(KIDIA:KFDIA,1:NCSS)=0._JPRB
    DO JTILE=1,NTILES
      PSURFL%ZFRSOTI(KIDIA:KFDIA,JTILE)=PFLUX%PFRSO(KIDIA:KFDIA,NLEV)
      ZSURF%PUSTRTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PVSTRTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PAHFSTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PEVAPTI(KIDIA:KFDIA,JTILE)=0._JPRB
      ZSURF%PTSKTI(KIDIA:KFDIA,JTILE)=ZSURF%GSP%PTL(KIDIA:KFDIA)
    ENDDO
  ENDIF
ENDDO
!$OMP END DO
!$OMP END PARALLEL

IF (LHOOK) CALL DR_HOOK('VDFMAIN1S_LAYER_OPENMP',1,ZHOOK_HANDLE)
END SUBROUTINE VDFMAIN1S_LAYER_OPENMP

END MODULE VDFMAIN1S_LAYER_MOD
